export enum EstadoSolicitud {
  BORRADOR = 'BORRADOR',
  PENDIENTE = 'PENDIENTE',
  RADICADA = 'RADICADA',
  EXTEMPORANEA = 'EXTEMPORANEA',
  SOLICITADO = 'SOLICITADO',
  APROBADO_JEFE = 'APROBADO_JEFE',
  APROBADO_TALENTO_HUMANO = 'APROBADO_TALENTO_HUMANO',
  RESOLUCION_EMITIDA = 'RESOLUCION_EMITIDA',
  TIQUETES_COMPRADOS = 'TIQUETES_COMPRADOS',
  EN_COMISION = 'EN_COMISION',
  PENDIENTE_LEGALIZACION = 'PENDIENTE_LEGALIZACION',
  LEGALIZADO = 'LEGALIZADO',
  RECHAZADO = 'RECHAZADO',
}

export const ESTADOS_SOLICITUD = Object.values(EstadoSolicitud);
