-- WARNING: This will wipe auth.permission and auth.module and reload from permissions-config-updated.ts
TRUNCATE TABLE auth.permission RESTART IDENTITY CASCADE;
TRUNCATE TABLE auth.module RESTART IDENTITY CASCADE;

-- Modules
INSERT INTO auth.module (code, name, description, icon, color, display_order, category) VALUES
  ('control_interno', 'Control Interno de Gestión', 'Control Interno de Gestión', 'ClipboardList', '#003DA5', 0, 'backoffice'),
  ('control_disciplinario', 'Control Disciplinario', 'Control Disciplinario', 'Scale', '#003DA5', 1, 'backoffice'),
  ('gestion_legal', 'Gestión Legal (SIGL)', 'Gestión Legal (SIGL)', 'ScrollText', '#003DA5', 2, 'backoffice'),
  ('certificados_laborales', 'Certificados Laborales', 'Certificados Laborales', 'FileCheck', '#003DA5', 3, 'backoffice'),
  ('firma_electronica', 'Firma Electrónica', 'Firma Electrónica', 'Pen', '#003DA5', 4, 'backoffice'),
  ('usuarios', 'Gestión de Usuarios', 'Gestión de Usuarios', 'Users', '#003DA5', 5, 'backoffice'),
  ('carpeta_digital', 'Carpeta Digital', 'Carpeta Digital', 'FolderOpen', '#003DA5', 6, 'backoffice'),
  ('roles_permisos', 'Roles y Permisos', 'Roles y Permisos', 'Shield', '#003DA5', 7, 'backoffice'),
  ('graduados', 'Graduados', 'Graduados', 'Award', '#003DA5', 8, 'backoffice'),
  ('enrolamiento', 'Enrolamiento', 'Enrolamiento', 'UserPlus', '#003DA5', 9, 'backoffice'),
  ('comunidad_publicaciones', 'Comunidad - Publicaciones', 'Comunidad - Publicaciones', 'MessageSquare', '#003DA5', 10, 'backoffice'),
  ('comunidad_eventos', 'Comunidad - Eventos', 'Comunidad - Eventos', 'CalendarDays', '#003DA5', 11, 'backoffice'),
  ('comunidad_anuncios', 'Comunidad - Anuncios', 'Comunidad - Anuncios', 'Bell', '#003DA5', 12, 'backoffice'),
  ('bolsa_empleo', 'Bolsa de Empleo', 'Bolsa de Empleo', 'Briefcase', '#003DA5', 13, 'backoffice'),
  ('estructura_organizacional', 'Estructura Organizacional', 'Estructura Organizacional', 'Building2', '#003DA5', 14, 'backoffice'),
  ('programas_academicos', 'Programas Académicos', 'Programas Académicos', 'GraduationCap', '#003DA5', 15, 'backoffice'),
  ('arquitectura_empresarial', 'Arquitectura Empresarial', 'Arquitectura Empresarial', 'Layers', '#003DA5', 16, 'backoffice'),
  ('gestion_profesoral', 'Gestión Profesoral', 'Gestión Profesoral', 'BookOpen', '#003DA5', 17, 'backoffice'),
  ('gestion_passwords', 'Gestión de Passwords', 'Gestión de Passwords', 'Lock', '#003DA5', 18, 'backoffice'),
  ('reportes', 'Informes y Reportes', 'Informes y Reportes', 'BarChart3', '#003DA5', 19, 'backoffice'),
  ('auditoria', 'Auditoría de Cambios', 'Auditoría de Cambios', 'Activity', '#003DA5', 20, 'backoffice');

-- Permissions
INSERT INTO auth.permission (code, name, description, id_module)
SELECT p.code, p.name, p.description, m.id_module
FROM (VALUES
  ('control_interno.dashboard.view', 'Ver Dashboard', 'Acceso al panel principal de Control Interno', 'control_interno'),
  ('control_interno.export.reports', 'Exportar Reportes', 'Descargar informes en Excel/PDF', 'control_interno'),
  ('control_interno.plan.view', 'Ver Plan Anual', 'Consultar Plan Anual de Auditoría', 'control_interno'),
  ('control_interno.plan.create', 'Crear Plan Anual', 'Generar nuevo Plan Anual', 'control_interno'),
  ('control_interno.plan.edit', 'Editar Plan Anual', 'Modificar Plan Anual existente', 'control_interno'),
  ('control_interno.plan.approve', 'Aprobar Plan Anual', 'Aprobar Plan Anual para ejecución', 'control_interno'),
  ('control_interno.plan.export', 'Exportar Plan', 'Descargar Plan Anual', 'control_interno'),
  ('control_interno.audit.view', 'Ver Auditorías', 'Consultar auditorías registradas', 'control_interno'),
  ('control_interno.audit.create', 'Crear Auditoría', 'Registrar nueva auditoría', 'control_interno'),
  ('control_interno.audit.edit', 'Editar Auditoría', 'Modificar auditoría existente', 'control_interno'),
  ('control_interno.audit.delete', 'Eliminar Auditoría', 'Eliminar auditoría del sistema', 'control_interno'),
  ('control_interno.audit.assign', 'Asignar Equipo Auditor', 'Asignar auditores a procesos', 'control_interno'),
  ('control_interno.audit.close', 'Cerrar Auditoría', 'Finalizar y cerrar auditoría', 'control_interno'),
  ('control_interno.finding.view', 'Ver Hallazgos', 'Consultar hallazgos detectados', 'control_interno'),
  ('control_interno.finding.create', 'Crear Hallazgo', 'Registrar nuevo hallazgo', 'control_interno'),
  ('control_interno.finding.edit', 'Editar Hallazgo', 'Modificar hallazgo existente', 'control_interno'),
  ('control_interno.finding.classify', 'Clasificar Hallazgo', 'Categorizar criticidad de hallazgo', 'control_interno'),
  ('control_interno.improvement.view', 'Ver Planes de Mejoramiento', 'Consultar planes de mejoramiento', 'control_interno'),
  ('control_interno.improvement.create', 'Crear Plan de Mejoramiento', 'Generar nuevo plan de mejoramiento', 'control_interno'),
  ('control_interno.improvement.edit', 'Editar Plan', 'Modificar plan de mejoramiento', 'control_interno'),
  ('control_interno.improvement.approve', 'Aprobar Plan', 'Aprobar plan de mejoramiento', 'control_interno'),
  ('control_interno.improvement.track', 'Hacer Seguimiento', 'Actualizar avance de plan', 'control_interno'),
  ('control_interno.improvement.close', 'Cerrar Plan', 'Finalizar plan completado', 'control_interno'),
  ('control_interno.evidence.view', 'Ver Evidencias', 'Consultar evidencias cargadas', 'control_interno'),
  ('control_interno.evidence.upload', 'Cargar Evidencias', 'Subir documentos de evidencia', 'control_interno'),
  ('control_interno.evidence.validate', 'Validar Evidencias', 'Aprobar/Rechazar evidencias', 'control_interno'),
  ('control_interno.evidence.delete', 'Eliminar Evidencias', 'Borrar evidencias del sistema', 'control_interno'),
  ('control_interno.legal_report.view', 'Ver Informes de Ley', 'Consultar informes pormenorizados', 'control_interno'),
  ('control_interno.legal_report.create', 'Crear Informe de Ley', 'Generar informe pormenorizado', 'control_interno'),
  ('control_interno.legal_report.edit', 'Editar Informe', 'Modificar informe de ley', 'control_interno'),
  ('control_interno.legal_report.approve', 'Aprobar Informe', 'Aprobar informe para publicación', 'control_interno'),
  ('control_interno.legal_report.publish', 'Publicar Informe', 'Publicar en portal web', 'control_interno'),
  ('control_interno.legal_report.send', 'Enviar a Entidades', 'Enviar a entes de control', 'control_interno'),
  ('control_interno.risk.view', 'Ver Mapa de Riesgos', 'Consultar matriz de riesgos', 'control_interno'),
  ('control_interno.risk.create', 'Crear Riesgo', 'Registrar nuevo riesgo', 'control_interno'),
  ('control_interno.risk.edit', 'Editar Riesgo', 'Modificar riesgo existente', 'control_interno'),
  ('control_interno.risk.assess', 'Evaluar Riesgo', 'Calcular probabilidad e impacto', 'control_interno'),
  ('control_interno.risk.mitigate', 'Crear Plan de Mitigación', 'Definir controles de mitigación', 'control_interno'),
  ('control_interno.config.view', 'Ver Configuraciones', 'Consultar configuraciones del módulo', 'control_interno'),
  ('control_interno.config.edit', 'Editar Configuraciones', 'Modificar parámetros del sistema', 'control_interno'),
  ('control_interno.config.users', 'Gestionar Usuarios CIG', 'Administrar usuarios de Control Interno', 'control_interno'),
  ('control_disciplinario.dashboard.view', 'Ver Dashboard', 'Panel principal de Control Disciplinario', 'control_disciplinario'),
  ('control_disciplinario.complaint.view', 'Ver Quejas', 'Consultar quejas y denuncias', 'control_disciplinario'),
  ('control_disciplinario.complaint.create', 'Crear Queja', 'Registrar nueva queja', 'control_disciplinario'),
  ('control_disciplinario.complaint.edit', 'Editar Queja', 'Modificar queja existente', 'control_disciplinario'),
  ('control_disciplinario.complaint.classify', 'Clasificar Queja', 'Categorizar tipo de queja', 'control_disciplinario'),
  ('control_disciplinario.process.view', 'Ver Procesos', 'Consultar procesos disciplinarios', 'control_disciplinario'),
  ('control_disciplinario.process.create', 'Iniciar Proceso', 'Abrir nuevo proceso disciplinario', 'control_disciplinario'),
  ('control_disciplinario.process.edit', 'Editar Proceso', 'Modificar datos del proceso', 'control_disciplinario'),
  ('control_disciplinario.process.close', 'Cerrar Proceso', 'Finalizar proceso disciplinario', 'control_disciplinario'),
  ('control_disciplinario.process.archive', 'Archivar Proceso', 'Archivar proceso sin sanción', 'control_disciplinario'),
  ('control_disciplinario.document.view', 'Ver Documentos', 'Consultar autos y resoluciones', 'control_disciplinario'),
  ('control_disciplinario.document.create_auto', 'Crear Auto', 'Generar auto disciplinario', 'control_disciplinario'),
  ('control_disciplinario.document.create_resolution', 'Crear Resolución', 'Generar resolución sancionatoria', 'control_disciplinario'),
  ('control_disciplinario.document.edit', 'Editar Documento', 'Modificar auto/resolución', 'control_disciplinario'),
  ('control_disciplinario.document.sign', 'Firmar Documento', 'Firmar digitalmente documentos', 'control_disciplinario'),
  ('control_disciplinario.document.notify', 'Notificar Acto', 'Notificar formalmente al investigado', 'control_disciplinario'),
  ('control_disciplinario.sanction.view', 'Ver Sanciones', 'Consultar sanciones impuestas', 'control_disciplinario'),
  ('control_disciplinario.sanction.apply', 'Aplicar Sanción', 'Imponer sanción disciplinaria', 'control_disciplinario'),
  ('control_disciplinario.sanction.track', 'Hacer Seguimiento', 'Monitorear cumplimiento de sanción', 'control_disciplinario'),
  ('control_disciplinario.sanction.close', 'Cerrar Sanción', 'Finalizar sanción cumplida', 'control_disciplinario'),
  ('control_disciplinario.stage.indagacion', 'Indagación Preliminar', 'Gestionar etapa de indagación', 'control_disciplinario'),
  ('control_disciplinario.stage.investigacion', 'Investigación Formal', 'Gestionar investigación disciplinaria', 'control_disciplinario'),
  ('control_disciplinario.stage.juzgamiento', 'Etapa de Juzgamiento', 'Gestionar juzgamiento disciplinario', 'control_disciplinario'),
  ('control_disciplinario.docs.upload', 'Cargar Documentos', 'Subir documentos al expediente', 'control_disciplinario'),
  ('control_disciplinario.docs.download', 'Descargar Documentos', 'Descargar documentos del expediente', 'control_disciplinario'),
  ('control_disciplinario.docs.delete', 'Eliminar Documentos', 'Borrar documentos del expediente', 'control_disciplinario'),
  ('control_disciplinario.export.report', 'Exportar Reportes', 'Generar informes en PDF/Excel', 'control_disciplinario'),
  ('control_disciplinario.stats.view', 'Ver Estadísticas', 'Consultar métricas del módulo', 'control_disciplinario'),
  ('control_disciplinario.config.view', 'Ver Configuraciones', 'Consultar configuraciones', 'control_disciplinario'),
  ('control_disciplinario.config.edit', 'Editar Configuraciones', 'Modificar parámetros del sistema', 'control_disciplinario'),
  ('gestion_legal.dashboard.view', 'Ver Dashboard', 'Panel principal de Gestión Legal', 'gestion_legal'),
  ('gestion_legal.expediente.view', 'Ver Expedientes', 'Consultar expedientes legales', 'gestion_legal'),
  ('gestion_legal.expediente.create', 'Crear Expediente', 'Registrar nuevo expediente legal', 'gestion_legal'),
  ('gestion_legal.expediente.edit', 'Editar Expediente', 'Modificar expediente existente', 'gestion_legal'),
  ('gestion_legal.expediente.close', 'Cerrar Expediente', 'Finalizar expediente', 'gestion_legal'),
  ('gestion_legal.expediente.assign', 'Asignar Abogado', 'Asignar responsable legal', 'gestion_legal'),
  ('gestion_legal.tutela.manage', 'Gestionar Tutelas', 'Administrar acciones de tutela', 'gestion_legal'),
  ('gestion_legal.demanda.manage', 'Gestionar Demandas', 'Administrar demandas', 'gestion_legal'),
  ('gestion_legal.conciliacion.manage', 'Gestionar Conciliaciones', 'Administrar conciliaciones', 'gestion_legal'),
  ('gestion_legal.proceso_coactivo.manage', 'Gestionar Procesos Coactivos', 'Administrar cobro coactivo', 'gestion_legal'),
  ('gestion_legal.concepto.view', 'Ver Conceptos Jurídicos', 'Consultar conceptos emitidos', 'gestion_legal'),
  ('gestion_legal.concepto.create', 'Crear Concepto Jurídico', 'Emitir concepto jurídico', 'gestion_legal'),
  ('gestion_legal.concepto.edit', 'Editar Concepto', 'Modificar concepto jurídico', 'gestion_legal'),
  ('gestion_legal.concepto.approve', 'Aprobar Concepto', 'Aprobar concepto para notificación', 'gestion_legal'),
  ('gestion_legal.contract.view', 'Ver Contratos', 'Consultar contratos registrados', 'gestion_legal'),
  ('gestion_legal.contract.create', 'Crear Contrato', 'Registrar nuevo contrato', 'gestion_legal'),
  ('gestion_legal.contract.edit', 'Editar Contrato', 'Modificar contrato existente', 'gestion_legal'),
  ('gestion_legal.contract.approve', 'Aprobar Contrato', 'Aprobar contrato para firma', 'gestion_legal'),
  ('gestion_legal.docs.upload', 'Cargar Documentos', 'Subir documentos al expediente', 'gestion_legal'),
  ('gestion_legal.docs.download', 'Descargar Documentos', 'Descargar documentos', 'gestion_legal'),
  ('gestion_legal.docs.delete', 'Eliminar Documentos', 'Borrar documentos', 'gestion_legal'),
  ('gestion_legal.tracking.view', 'Ver Trazabilidad', 'Consultar historial de acciones', 'gestion_legal'),
  ('gestion_legal.export.report', 'Exportar Reportes', 'Generar informes en PDF/Excel', 'gestion_legal'),
  ('gestion_legal.stats.view', 'Ver Estadísticas', 'Consultar métricas del módulo', 'gestion_legal'),
  ('gestion_legal.config.view', 'Ver Configuraciones', 'Consultar configuraciones', 'gestion_legal'),
  ('gestion_legal.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'gestion_legal'),
  ('certificados_laborales.dashboard.view', 'Ver Dashboard', 'Panel principal de certificados', 'certificados_laborales'),
  ('certificados_laborales.request.view', 'Ver Solicitudes', 'Consultar solicitudes de certificados', 'certificados_laborales'),
  ('certificados_laborales.request.create', 'Crear Solicitud', 'Generar nueva solicitud', 'certificados_laborales'),
  ('certificados_laborales.certificate.generate', 'Generar Certificado', 'Emitir certificado laboral', 'certificados_laborales'),
  ('certificados_laborales.certificate.approve', 'Aprobar Certificado', 'Aprobar certificado para entrega', 'certificados_laborales'),
  ('certificados_laborales.certificate.sign', 'Firmar Certificado', 'Firmar digitalmente certificado', 'certificados_laborales'),
  ('certificados_laborales.certificate.deliver', 'Entregar Certificado', 'Marcar como entregado', 'certificados_laborales'),
  ('certificados_laborales.certificate.verify', 'Verificar Certificado', 'Validar autenticidad mediante QR', 'certificados_laborales'),
  ('certificados_laborales.certificate.revoke', 'Revocar Certificado', 'Anular certificado emitido', 'certificados_laborales'),
  ('certificados_laborales.template.manage', 'Gestionar Plantillas', 'Administrar plantillas de certificados', 'certificados_laborales'),
  ('certificados_laborales.export.report', 'Exportar Reportes', 'Generar informes', 'certificados_laborales'),
  ('certificados_laborales.stats.view', 'Ver Estadísticas', 'Consultar métricas', 'certificados_laborales'),
  ('certificados_laborales.notification.send', 'Enviar Notificaciones', 'Notificar al solicitante', 'certificados_laborales'),
  ('certificados_laborales.history.view', 'Ver Histórico', 'Consultar histórico de validaciones', 'certificados_laborales'),
  ('certificados_laborales.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'certificados_laborales'),
  ('firma_electronica.dashboard.view', 'Ver Dashboard', 'Panel principal de firma electrónica', 'firma_electronica'),
  ('firma_electronica.document.upload', 'Cargar Documento', 'Subir documento para firma', 'firma_electronica'),
  ('firma_electronica.signature.request', 'Solicitar Firma', 'Enviar solicitud de firma', 'firma_electronica'),
  ('firma_electronica.signature.sign', 'Firmar Documento', 'Firmar digitalmente documento', 'firma_electronica'),
  ('firma_electronica.signature.reject', 'Rechazar Firma', 'Rechazar solicitud de firma', 'firma_electronica'),
  ('firma_electronica.signature.verify', 'Verificar Firma', 'Validar autenticidad de firma', 'firma_electronica'),
  ('firma_electronica.document.download', 'Descargar Documento', 'Descargar documento firmado', 'firma_electronica'),
  ('firma_electronica.workflow.view', 'Ver Flujos de Firma', 'Consultar workflows de firma', 'firma_electronica'),
  ('firma_electronica.workflow.create', 'Crear Flujo', 'Configurar workflow de firma', 'firma_electronica'),
  ('firma_electronica.history.view', 'Ver Histórico', 'Consultar histórico de firmas', 'firma_electronica'),
  ('firma_electronica.stats.view', 'Ver Estadísticas', 'Consultar métricas', 'firma_electronica'),
  ('firma_electronica.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'firma_electronica'),
  ('usuarios.view', 'Ver Usuarios', 'Consultar lista de usuarios', 'usuarios'),
  ('usuarios.create', 'Crear Usuario', 'Registrar nuevo usuario', 'usuarios'),
  ('usuarios.edit', 'Editar Usuario', 'Modificar datos de usuario', 'usuarios'),
  ('usuarios.delete', 'Eliminar Usuario', 'Dar de baja usuario', 'usuarios'),
  ('usuarios.activate', 'Activar/Desactivar', 'Cambiar estado de usuario', 'usuarios'),
  ('usuarios.reset_password', 'Restablecer Contraseña', 'Resetear contraseña de usuario', 'usuarios'),
  ('usuarios.assign_role', 'Asignar Rol', 'Asignar roles a usuario', 'usuarios'),
  ('usuarios.remove_role', 'Revocar Rol', 'Quitar roles de usuario', 'usuarios'),
  ('usuarios.assign_territorial', 'Asignar Territorial', 'Vincular a dirección territorial', 'usuarios'),
  ('usuarios.assign_sede', 'Asignar Sede', 'Vincular a sede específica', 'usuarios'),
  ('usuarios.view_persona', 'Ver Modelo Persona', 'Consultar modelo Usuario Persona', 'usuarios'),
  ('usuarios.manage_persona', 'Gestionar Persona', 'Administrar múltiples roles por persona', 'usuarios'),
  ('usuarios.view_enrollment', 'Ver Vinculaciones', 'Consultar vinculaciones académicas', 'usuarios'),
  ('usuarios.export', 'Exportar Usuarios', 'Descargar datos en Excel/CSV', 'usuarios'),
  ('usuarios.import', 'Importar Usuarios', 'Carga masiva de usuarios', 'usuarios'),
  ('usuarios.view_audit', 'Ver Auditoría', 'Consultar log de cambios', 'usuarios'),
  ('usuarios.manage_2fa', 'Gestionar 2FA', 'Administrar autenticación de dos factores', 'usuarios'),
  ('usuarios.view_stats', 'Ver Estadísticas', 'Consultar métricas de usuarios', 'usuarios'),
  ('usuarios.send_notification', 'Enviar Notificaciones', 'Notificar a usuarios', 'usuarios'),
  ('usuarios.config.edit', 'Editar Configuraciones', 'Modificar parámetros del módulo', 'usuarios'),
  ('carpeta_digital.view', 'Ver Carpeta Digital', 'Consultar carpeta digital de usuarios', 'carpeta_digital'),
  ('carpeta_digital.upload', 'Cargar Documentos', 'Subir documentos a carpeta digital', 'carpeta_digital'),
  ('carpeta_digital.download', 'Descargar Documentos', 'Descargar documentos de carpeta', 'carpeta_digital'),
  ('carpeta_digital.delete', 'Eliminar Documentos', 'Borrar documentos de carpeta', 'carpeta_digital'),
  ('carpeta_digital.organize', 'Organizar Carpetas', 'Crear y gestionar categorías', 'carpeta_digital'),
  ('carpeta_digital.validate', 'Validar Documentos', 'Aprobar/Rechazar documentos', 'carpeta_digital'),
  ('carpeta_digital.share', 'Compartir Documentos', 'Compartir documentos con otros usuarios', 'carpeta_digital'),
  ('carpeta_digital.version_control', 'Control de Versiones', 'Gestionar versiones de documentos', 'carpeta_digital'),
  ('carpeta_digital.export', 'Exportar Carpeta', 'Descargar carpeta completa', 'carpeta_digital'),
  ('carpeta_digital.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'carpeta_digital'),
  ('roles_permisos.view', 'Ver Roles', 'Consultar roles del sistema', 'roles_permisos'),
  ('roles_permisos.create', 'Crear Rol', 'Registrar nuevo rol', 'roles_permisos'),
  ('roles_permisos.edit', 'Editar Rol', 'Modificar rol existente', 'roles_permisos'),
  ('roles_permisos.delete', 'Eliminar Rol', 'Borrar rol del sistema', 'roles_permisos'),
  ('roles_permisos.assign_permissions', 'Asignar Permisos', 'Configurar permisos granulares', 'roles_permisos'),
  ('roles_permisos.revoke_permissions', 'Revocar Permisos', 'Quitar permisos de rol', 'roles_permisos'),
  ('roles_permisos.clone', 'Clonar Rol', 'Duplicar rol existente', 'roles_permisos'),
  ('roles_permisos.view_users', 'Ver Usuarios del Rol', 'Consultar usuarios asignados', 'roles_permisos'),
  ('roles_permisos.export', 'Exportar Roles', 'Descargar configuración de roles', 'roles_permisos'),
  ('roles_permisos.audit', 'Ver Auditoría', 'Consultar cambios en roles y permisos', 'roles_permisos'),
  ('graduados.view', 'Ver Graduados', 'Consultar base de datos de graduados', 'graduados'),
  ('graduados.create', 'Registrar Graduado', 'Registrar nuevo graduado', 'graduados'),
  ('graduados.edit', 'Editar Graduado', 'Modificar datos de graduado', 'graduados'),
  ('graduados.delete', 'Eliminar Graduado', 'Dar de baja graduado', 'graduados'),
  ('graduados.generate_diploma', 'Generar Diploma', 'Emitir diploma de grado', 'graduados'),
  ('graduados.generate_certificate', 'Generar Certificado', 'Emitir certificado de título', 'graduados'),
  ('graduados.verify_certificate', 'Verificar Certificado', 'Validar autenticidad mediante QR', 'graduados'),
  ('graduados.revoke_certificate', 'Revocar Certificado', 'Anular certificado emitido', 'graduados'),
  ('graduados.view_academic_record', 'Ver Registro Académico', 'Consultar historial académico', 'graduados'),
  ('graduados.edit_academic_record', 'Editar Registro', 'Modificar datos académicos', 'graduados'),
  ('graduados.export', 'Exportar Graduados', 'Descargar datos de graduados', 'graduados'),
  ('graduados.view_stats', 'Ver Estadísticas', 'Consultar métricas de graduados', 'graduados'),
  ('graduados.send_notification', 'Enviar Notificaciones', 'Notificar a graduados', 'graduados'),
  ('graduados.manage_honors', 'Gestionar Honores', 'Asignar menciones y reconocimientos', 'graduados'),
  ('graduados.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'graduados'),
  ('enrolamiento.view', 'Ver Enrolamientos', 'Consultar procesos de enrolamiento', 'enrolamiento'),
  ('enrolamiento.individual', 'Enrolar Individual', 'Enrolar usuario individualmente', 'enrolamiento'),
  ('enrolamiento.massive', 'Enrolar Masivo', 'Enrolar usuarios en lote', 'enrolamiento'),
  ('enrolamiento.import', 'Importar Excel', 'Cargar archivo de enrolamiento masivo', 'enrolamiento'),
  ('enrolamiento.validate', 'Validar Enrolamiento', 'Aprobar/Rechazar enrolamiento', 'enrolamiento'),
  ('enrolamiento.cancel', 'Cancelar Enrolamiento', 'Anular proceso de enrolamiento', 'enrolamiento'),
  ('enrolamiento.view_history', 'Ver Histórico', 'Consultar histórico de enrolamientos', 'enrolamiento'),
  ('enrolamiento.export', 'Exportar Enrolamientos', 'Descargar reportes', 'enrolamiento'),
  ('enrolamiento.view_stats', 'Ver Estadísticas', 'Consultar métricas', 'enrolamiento'),
  ('enrolamiento.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'enrolamiento'),
  ('comunidad_publicaciones.view', 'Ver Publicaciones', 'Consultar publicaciones de comunidad', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.create', 'Crear Publicación', 'Publicar contenido en comunidad', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.edit', 'Editar Publicación', 'Modificar publicación existente', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.delete', 'Eliminar Publicación', 'Borrar publicación', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.moderate', 'Moderar Publicaciones', 'Aprobar/Rechazar publicaciones', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.pin', 'Fijar Publicación', 'Destacar publicación importante', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.comment', 'Comentar', 'Comentar en publicaciones', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.react', 'Reaccionar', 'Dar me gusta/reacciones', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.share', 'Compartir', 'Compartir publicaciones', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.report', 'Reportar', 'Reportar contenido inapropiado', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.export', 'Exportar Publicaciones', 'Descargar reportes', 'comunidad_publicaciones'),
  ('comunidad_publicaciones.stats.view', 'Ver Estadísticas', 'Consultar métricas de engagement', 'comunidad_publicaciones'),
  ('comunidad_eventos.view', 'Ver Eventos', 'Consultar eventos publicados', 'comunidad_eventos'),
  ('comunidad_eventos.create', 'Crear Evento', 'Publicar nuevo evento', 'comunidad_eventos'),
  ('comunidad_eventos.edit', 'Editar Evento', 'Modificar evento existente', 'comunidad_eventos'),
  ('comunidad_eventos.delete', 'Eliminar Evento', 'Borrar evento', 'comunidad_eventos'),
  ('comunidad_eventos.publish', 'Publicar Evento', 'Publicar evento para comunidad', 'comunidad_eventos'),
  ('comunidad_eventos.cancel', 'Cancelar Evento', 'Cancelar evento programado', 'comunidad_eventos'),
  ('comunidad_eventos.manage_attendees', 'Gestionar Asistentes', 'Administrar confirmaciones de asistencia', 'comunidad_eventos'),
  ('comunidad_eventos.send_reminders', 'Enviar Recordatorios', 'Notificar a asistentes registrados', 'comunidad_eventos'),
  ('comunidad_eventos.export', 'Exportar Eventos', 'Descargar reportes', 'comunidad_eventos'),
  ('comunidad_eventos.stats.view', 'Ver Estadísticas', 'Consultar métricas de eventos', 'comunidad_eventos'),
  ('comunidad_anuncios.view', 'Ver Anuncios', 'Consultar anuncios publicados', 'comunidad_anuncios'),
  ('comunidad_anuncios.create', 'Crear Anuncio', 'Publicar nuevo anuncio', 'comunidad_anuncios'),
  ('comunidad_anuncios.edit', 'Editar Anuncio', 'Modificar anuncio existente', 'comunidad_anuncios'),
  ('comunidad_anuncios.delete', 'Eliminar Anuncio', 'Borrar anuncio', 'comunidad_anuncios'),
  ('comunidad_anuncios.publish', 'Publicar Anuncio', 'Publicar para toda la comunidad', 'comunidad_anuncios'),
  ('comunidad_anuncios.target', 'Segmentar Audiencia', 'Enviar a grupos específicos', 'comunidad_anuncios'),
  ('comunidad_anuncios.schedule', 'Programar Anuncio', 'Programar publicación futura', 'comunidad_anuncios'),
  ('comunidad_anuncios.stats.view', 'Ver Estadísticas', 'Consultar métricas de alcance', 'comunidad_anuncios'),
  ('bolsa_empleo.view', 'Ver Ofertas', 'Consultar ofertas de empleo', 'bolsa_empleo'),
  ('bolsa_empleo.create', 'Publicar Oferta', 'Crear nueva oferta de empleo', 'bolsa_empleo'),
  ('bolsa_empleo.edit', 'Editar Oferta', 'Modificar oferta existente', 'bolsa_empleo'),
  ('bolsa_empleo.delete', 'Eliminar Oferta', 'Borrar oferta de empleo', 'bolsa_empleo'),
  ('bolsa_empleo.activate', 'Activar/Desactivar', 'Cambiar estado de oferta', 'bolsa_empleo'),
  ('bolsa_empleo.view_applications', 'Ver Postulaciones', 'Consultar candidatos postulados', 'bolsa_empleo'),
  ('bolsa_empleo.review_application', 'Revisar Postulación', 'Evaluar candidato', 'bolsa_empleo'),
  ('bolsa_empleo.contact_candidate', 'Contactar Candidato', 'Enviar mensaje a postulante', 'bolsa_empleo'),
  ('bolsa_empleo.manage_companies', 'Gestionar Empresas', 'Administrar empresas registradas', 'bolsa_empleo'),
  ('bolsa_empleo.export', 'Exportar Reportes', 'Descargar datos de ofertas', 'bolsa_empleo'),
  ('bolsa_empleo.stats.view', 'Ver Estadísticas', 'Consultar métricas de empleabilidad', 'bolsa_empleo'),
  ('bolsa_empleo.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'bolsa_empleo'),
  ('estructura_organizacional.view', 'Ver Estructura', 'Consultar estructura organizacional', 'estructura_organizacional'),
  ('estructura_organizacional.view_territorial', 'Ver Territoriales', 'Consultar 17 direcciones territoriales', 'estructura_organizacional'),
  ('estructura_organizacional.view_sedes', 'Ver Sedes', 'Consultar 71+ sedes ESAP', 'estructura_organizacional'),
  ('estructura_organizacional.create_dependencia', 'Crear Dependencia', 'Registrar nueva dependencia', 'estructura_organizacional'),
  ('estructura_organizacional.edit_dependencia', 'Editar Dependencia', 'Modificar dependencia existente', 'estructura_organizacional'),
  ('estructura_organizacional.delete_dependencia', 'Eliminar Dependencia', 'Borrar dependencia', 'estructura_organizacional'),
  ('estructura_organizacional.create_cargo', 'Crear Cargo', 'Registrar nuevo cargo', 'estructura_organizacional'),
  ('estructura_organizacional.edit_cargo', 'Editar Cargo', 'Modificar cargo existente', 'estructura_organizacional'),
  ('estructura_organizacional.delete_cargo', 'Eliminar Cargo', 'Borrar cargo', 'estructura_organizacional'),
  ('estructura_organizacional.assign_users', 'Asignar Usuarios', 'Vincular usuarios a dependencias', 'estructura_organizacional'),
  ('estructura_organizacional.view_hierarchy', 'Ver Jerarquía', 'Visualizar organigrama completo', 'estructura_organizacional'),
  ('estructura_organizacional.view_map', 'Ver Mapa', 'Ver sedes en mapa de Colombia', 'estructura_organizacional'),
  ('estructura_organizacional.export', 'Exportar Estructura', 'Descargar organigrama', 'estructura_organizacional'),
  ('estructura_organizacional.stats.view', 'Ver Estadísticas', 'Consultar métricas organizacionales', 'estructura_organizacional'),
  ('estructura_organizacional.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'estructura_organizacional'),
  ('programas_academicos.view', 'Ver Programas', 'Consultar programas académicos', 'programas_academicos'),
  ('programas_academicos.create', 'Crear Programa', 'Registrar nuevo programa', 'programas_academicos'),
  ('programas_academicos.edit', 'Editar Programa', 'Modificar programa existente', 'programas_academicos'),
  ('programas_academicos.delete', 'Eliminar Programa', 'Borrar programa académico', 'programas_academicos'),
  ('programas_academicos.view_curriculum', 'Ver Pensum', 'Consultar plan de estudios', 'programas_academicos'),
  ('programas_academicos.edit_curriculum', 'Editar Pensum', 'Modificar plan de estudios', 'programas_academicos'),
  ('programas_academicos.assign_sede', 'Asignar Sede', 'Vincular programa a sedes', 'programas_academicos'),
  ('programas_academicos.view_students', 'Ver Estudiantes', 'Consultar estudiantes matriculados', 'programas_academicos'),
  ('programas_academicos.activate', 'Activar/Desactivar', 'Cambiar estado de programa', 'programas_academicos'),
  ('programas_academicos.export', 'Exportar Programas', 'Descargar datos de programas', 'programas_academicos'),
  ('programas_academicos.stats.view', 'Ver Estadísticas', 'Consultar métricas académicas', 'programas_academicos'),
  ('programas_academicos.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'programas_academicos'),
  ('arquitectura_empresarial.view', 'Ver Arquitectura', 'Consultar arquitectura empresarial', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.view_capabilities', 'Ver Capacidades', 'Consultar mapa de capacidades', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.create_capability', 'Crear Capacidad', 'Documentar nueva capacidad', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.edit_capability', 'Editar Capacidad', 'Modificar capacidad existente', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.view_processes', 'Ver Procesos', 'Consultar procesos de negocio', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.create_process', 'Crear Proceso', 'Documentar nuevo proceso', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.edit_process', 'Editar Proceso', 'Modificar proceso existente', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.view_systems', 'Ver Sistemas', 'Consultar sistemas de información', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.create_system', 'Crear Sistema', 'Registrar nuevo sistema', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.edit_system', 'Editar Sistema', 'Modificar sistema existente', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.view_applications', 'Ver Aplicaciones', 'Consultar portafolio de aplicaciones', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.create_application', 'Crear Aplicación', 'Registrar nueva aplicación', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.export', 'Exportar Arquitectura', 'Descargar documentación', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.view_roadmap', 'Ver Roadmap', 'Consultar hoja de ruta tecnológica', 'arquitectura_empresarial'),
  ('arquitectura_empresarial.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'arquitectura_empresarial'),
  ('gestion_profesoral.view', 'Ver Docentes', 'Consultar información de docentes', 'gestion_profesoral'),
  ('gestion_profesoral.create', 'Crear Docente', 'Registrar nuevo docente', 'gestion_profesoral'),
  ('gestion_profesoral.edit', 'Editar Docente', 'Modificar datos de docente', 'gestion_profesoral'),
  ('gestion_profesoral.delete', 'Eliminar Docente', 'Dar de baja docente', 'gestion_profesoral'),
  ('gestion_profesoral.view_convocatoria', 'Ver Convocatorias', 'Consultar convocatorias docentes', 'gestion_profesoral'),
  ('gestion_profesoral.create_convocatoria', 'Crear Convocatoria', 'Publicar convocatoria docente', 'gestion_profesoral'),
  ('gestion_profesoral.evaluate_postulation', 'Evaluar Postulación', 'Evaluar candidatos docentes', 'gestion_profesoral'),
  ('gestion_profesoral.assign_load', 'Asignar Carga Académica', 'Gestionar horas y materias', 'gestion_profesoral'),
  ('gestion_profesoral.view_schedule', 'Ver Horarios', 'Consultar horarios docentes', 'gestion_profesoral'),
  ('gestion_profesoral.create_schedule', 'Crear Horarios', 'Generar horarios académicos', 'gestion_profesoral'),
  ('gestion_profesoral.evaluate_performance', 'Evaluar Desempeño', 'Realizar evaluación docente', 'gestion_profesoral'),
  ('gestion_profesoral.manage_contracts', 'Gestionar Contratos', 'Administrar contratos laborales', 'gestion_profesoral'),
  ('gestion_profesoral.export', 'Exportar Docentes', 'Descargar datos de docentes', 'gestion_profesoral'),
  ('gestion_profesoral.stats.view', 'Ver Estadísticas', 'Consultar métricas docentes', 'gestion_profesoral'),
  ('gestion_profesoral.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'gestion_profesoral'),
  ('gestion_passwords.view', 'Ver Políticas', 'Consultar políticas de contraseñas', 'gestion_passwords'),
  ('gestion_passwords.edit_policies', 'Editar Políticas', 'Modificar políticas de seguridad', 'gestion_passwords'),
  ('gestion_passwords.reset_user', 'Resetear Contraseña', 'Restablecer contraseña de usuario', 'gestion_passwords'),
  ('gestion_passwords.force_change', 'Forzar Cambio', 'Obligar cambio de contraseña', 'gestion_passwords'),
  ('gestion_passwords.view_history', 'Ver Histórico', 'Consultar histórico de cambios', 'gestion_passwords'),
  ('gestion_passwords.view_expiration', 'Ver Expiración', 'Consultar contraseñas por vencer', 'gestion_passwords'),
  ('gestion_passwords.send_reminder', 'Enviar Recordatorio', 'Notificar cambio de contraseña', 'gestion_passwords'),
  ('gestion_passwords.view_audit', 'Ver Auditoría', 'Consultar log de seguridad', 'gestion_passwords'),
  ('reportes.view', 'Ver Reportes', 'Consultar reportes del sistema', 'reportes'),
  ('reportes.create', 'Crear Reporte', 'Generar nuevo reporte', 'reportes'),
  ('reportes.customize', 'Personalizar Reporte', 'Configurar filtros y parámetros', 'reportes'),
  ('reportes.export_excel', 'Exportar a Excel', 'Descargar reporte en Excel', 'reportes'),
  ('reportes.export_pdf', 'Exportar a PDF', 'Descargar reporte en PDF', 'reportes'),
  ('reportes.export_csv', 'Exportar a CSV', 'Descargar reporte en CSV', 'reportes'),
  ('reportes.schedule', 'Programar Reporte', 'Automatizar generación de reportes', 'reportes'),
  ('reportes.share', 'Compartir Reporte', 'Compartir con otros usuarios', 'reportes'),
  ('reportes.view_dashboard', 'Ver Dashboards', 'Consultar dashboards analíticos', 'reportes'),
  ('reportes.config.edit', 'Editar Configuraciones', 'Modificar parámetros', 'reportes'),
  ('auditoria.view', 'Ver Logs de Auditoría', 'Consultar registros de auditoría', 'auditoria'),
  ('auditoria.view_details', 'Ver Detalles', 'Consultar detalles completos de logs', 'auditoria'),
  ('auditoria.filter', 'Filtrar Logs', 'Aplicar filtros avanzados', 'auditoria'),
  ('auditoria.search', 'Buscar Logs', 'Buscar en registros de auditoría', 'auditoria'),
  ('auditoria.export_excel', 'Exportar a Excel', 'Descargar logs en Excel', 'auditoria'),
  ('auditoria.export_pdf', 'Exportar a PDF', 'Descargar logs en PDF', 'auditoria'),
  ('auditoria.view_stats', 'Ver Estadísticas', 'Consultar métricas de auditoría', 'auditoria'),
  ('auditoria.view_by_user', 'Ver por Usuario', 'Filtrar logs por usuario', 'auditoria'),
  ('auditoria.view_by_module', 'Ver por Módulo', 'Filtrar logs por módulo', 'auditoria'),
  ('auditoria.config.edit', 'Editar Configuraciones', 'Modificar parámetros de auditoría', 'auditoria')
) AS p(code,name,description,module_code)
JOIN auth.module m ON m.code = p.module_code;