UPDATE auth.personas SET
  nom_largo = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(nom_largo, 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico'),
  nom_tercero = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(nom_tercero, 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico'),
  pri_apellido = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(pri_apellido, 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico'),
  seg_apellido = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(seg_apellido, 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico');

UPDATE control_interno.configuracion_profesionales_ocig SET
  rol_ocig = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(rol_ocig, 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico'),
  especialidades = string_to_array(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(array_to_string(especialidades, '|||'), 
    'C??rdenas', 'Cárdenas'), 'Mar??a', 'María'), 'Andr??s', 'Andrés'), 'Ram??rez', 'Ramírez'), 'L??pez', 'López'), 'Luc??a', 'Lucía'), 'G??mez', 'Gómez'), 'Sof??a', 'Sofía'), 'Rector??a', 'Rectoría'), 'Secretar??a', 'Secretaría'), 'Subdirecci??n', 'Subdirección'), 'Acad??mica', 'Académica'), 'Proyecci??n', 'Proyección'), 'Jur??dica', 'Jurídica'), 'Planeaci??n', 'Planeación'), 'S??nior', 'Sénior'), 'Coordinaci??n', 'Coordinación'), 'Estrat??gica', 'Estratégica'), 'T??cnico', 'Técnico'), '|||');
