import { DataSource } from 'typeorm';
import { InformeLey } from './entities/informe-ley.entity';

/**
 * Seed de los 20 Informes de Ley Obligatorios para ESAP
 * Basado en el componente frontend GestionInformesLey.tsx
 */
export const INFORMES_LEY_SEED: Omit<InformeLey, 'id' | 'createdAt' | 'updatedAt' | 'entregas'>[] = [
  {
    codigo: 'INF-CHIP',
    nombre: 'Información Contable Pública - CHIP',
    descripcion: 'Reporte mensual de ejecución presupuestal y estados financieros al Sistema CHIP de la Contaduría General',
    normativaBase: 'Resolución 357 de 2008 CGN',
    categoria: 'financiero',
    periodicidad: 'mensual',
    diaPresentacion: 15,
    entidadDestino: 'Contaduría General de la Nación',
    responsable: 'María Fernanda López',
    area: 'Gestión Financiera',
    areaResponsable: 'Gestión Financiera',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/chip.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 7,
    activo: true,
  },
  {
    codigo: 'INF-SECOP',
    nombre: 'Publicación Plan Anual de Adquisiciones',
    descripcion: 'Publicación y actualización del Plan Anual de Adquisiciones en el portal SECOP',
    normativaBase: 'Ley 1150 de 2007, Decreto 1082 de 2015',
    categoria: 'contractual',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Colombia Compra Eficiente - SECOP',
    responsable: 'Carlos Andrés Ruiz',
    area: 'Gestión Contractual',
    areaResponsable: 'Gestión Contractual',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/paa.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 15,
    activo: true,
  },
  {
    codigo: 'INF-SIRECI',
    nombre: 'Informe Trimestral de Cartera',
    descripcion: 'Reporte de cuentas por cobrar y gestión de cartera al Sistema de Información y Reporte de Cartera (SIRECI)',
    normativaBase: 'Circular 005 de 2013 MinHacienda',
    categoria: 'financiero',
    periodicidad: 'trimestral',
    diaPresentacion: 15,
    entidadDestino: 'Ministerio de Hacienda',
    responsable: 'María Fernanda López',
    area: 'Gestión Financiera',
    areaResponsable: 'Gestión Financiera',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/sireci.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 10,
    activo: true,
  },
  {
    codigo: 'INF-SIGEP',
    nombre: 'Actualización Información SIGEP',
    descripcion: 'Actualización de planta de personal y hojas de vida en el Sistema de Información de Gestión del Empleo Público',
    normativaBase: 'Decreto 1083 de 2015, Ley 909 de 2004',
    categoria: 'talento-humano',
    periodicidad: 'mensual',
    diaPresentacion: 10,
    entidadDestino: 'Función Pública - SIGEP',
    responsable: 'Lucila Villamil Avendaño',
    area: 'Talento Humano',
    areaResponsable: 'Talento Humano',
    tienePlantilla: false,
    requiereAprobacion: false,
    diasAnticipacionAlerta: 5,
    activo: true,
  },
  {
    codigo: 'INF-PQRS',
    nombre: 'Informe de PQRS',
    descripcion: 'Reporte trimestral de Peticiones, Quejas, Reclamos y Sugerencias recibidas y gestionadas',
    normativaBase: 'Ley 1755 de 2015, Ley 1437 de 2011',
    categoria: 'administrativo',
    periodicidad: 'trimestral',
    diaPresentacion: 20,
    entidadDestino: 'Procuraduría General de la Nación',
    responsable: 'Sandra Paola Montero',
    area: 'Atención al Ciudadano',
    areaResponsable: 'Atención al Ciudadano',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/pqrs.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 10,
    activo: true,
  },
  {
    codigo: 'INF-TRANSPARENCIA',
    nombre: 'Actualización Portal de Transparencia',
    descripcion: 'Actualización mensual de información en el portal de transparencia según Ley de Transparencia',
    normativaBase: 'Ley 1712 de 2014, Decreto 103 de 2015',
    categoria: 'transparencia',
    periodicidad: 'mensual',
    diaPresentacion: 5,
    entidadDestino: 'Portal Institucional - Ciudadanía',
    responsable: 'Fernando Ávila',
    area: 'Comunicaciones',
    areaResponsable: 'Comunicaciones',
    tienePlantilla: false,
    requiereAprobacion: true,
    diasAnticipacionAlerta: 3,
    activo: true,
  },
  {
    codigo: 'INF-SISBEN',
    nombre: 'Reporte de Afiliados al Sistema de Seguridad Social',
    descripcion: 'Reporte mensual de afiliaciones y pago de aportes al Sistema de Seguridad Social',
    normativaBase: 'Ley 100 de 1993, Ley 1122 de 2007',
    categoria: 'talento-humano',
    periodicidad: 'mensual',
    diaPresentacion: 10,
    entidadDestino: 'EPS y Administradoras',
    responsable: 'Lucila Villamil Avendaño',
    area: 'Talento Humano',
    areaResponsable: 'Talento Humano',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/sisben.xlsx',
    requiereAprobacion: false,
    diasAnticipacionAlerta: 5,
    activo: true,
  },
  {
    codigo: 'INF-SIA-OBSERVA',
    nombre: 'Informe de Contratación SIA OBSERVA',
    descripcion: 'Reporte trimestral de contratos celebrados al Sistema de Información de Contratación SIA OBSERVA',
    normativaBase: 'Decreto 1510 de 2013',
    categoria: 'contractual',
    periodicidad: 'trimestral',
    diaPresentacion: 30,
    entidadDestino: 'Contraloría General de la República',
    responsable: 'Carlos Andrés Ruiz',
    area: 'Gestión Contractual',
    areaResponsable: 'Gestión Contractual',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/sia-observa.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 10,
    activo: true,
  },
  {
    codigo: 'INF-MIPG',
    nombre: 'Autodiagnóstico MIPG',
    descripcion: 'Autodiagnóstico anual del Modelo Integrado de Planeación y Gestión',
    normativaBase: 'Decreto 1499 de 2017',
    categoria: 'control',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Función Pública',
    responsable: 'Sandra Paola Montero',
    area: 'Control Interno',
    areaResponsable: 'Control Interno',
    tienePlantilla: false,
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
  {
    codigo: 'INF-CONTROL-INTERNO',
    nombre: 'Informe Anual de Control Interno',
    descripcion: 'Informe de evaluación del Sistema de Control Interno según MECI',
    normativaBase: 'Ley 1474 de 2011, Decreto 1537 de 2001',
    categoria: 'control',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Rectoría y Consejo Directivo',
    responsable: 'Sandra Paola Montero',
    area: 'Control Interno',
    areaResponsable: 'Control Interno',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/control-interno.docx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
  {
    codigo: 'INF-AUSTERIDAD',
    nombre: 'Informe de Austeridad del Gasto',
    descripcion: 'Reporte cuatrimestral de medidas de austeridad implementadas',
    normativaBase: 'Decreto 1737 de 1998, Circular 001 de MinHacienda',
    categoria: 'financiero',
    periodicidad: 'cuatrimestral',
    diaPresentacion: 15,
    entidadDestino: 'Ministerio de Hacienda',
    responsable: 'María Fernanda López',
    area: 'Gestión Financiera',
    areaResponsable: 'Gestión Financiera',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/austeridad.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 10,
    activo: true,
  },
  {
    codigo: 'INF-RENDICION-CUENTAS',
    nombre: 'Informe de Rendición de Cuentas',
    descripcion: 'Informe anual de rendición de cuentas a la ciudadanía',
    normativaBase: 'Ley 489 de 1998, CONPES 3654',
    categoria: 'transparencia',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Ciudadanía y Partes Interesadas',
    responsable: 'Fernando Ávila',
    area: 'Comunicaciones',
    areaResponsable: 'Comunicaciones',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/rendicion-cuentas.pptx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 45,
    activo: true,
  },
  {
    codigo: 'INF-GESTION-AMBIENTAL',
    nombre: 'Plan de Gestión Ambiental',
    descripcion: 'Informe semestral de implementación del Plan de Gestión Ambiental',
    normativaBase: 'Resolución 242 de 2014 MinAmbiente',
    categoria: 'administrativo',
    periodicidad: 'semestral',
    diaPresentacion: 15,
    entidadDestino: 'Ministerio de Ambiente',
    responsable: 'Carlos Andrés Ruiz',
    area: 'Gestión Administrativa',
    areaResponsable: 'Gestión Administrativa',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/gestion-ambiental.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 15,
    activo: true,
  },
  {
    codigo: 'INF-SST',
    nombre: 'Informe de Seguridad y Salud en el Trabajo',
    descripcion: 'Reporte anual del Sistema de Gestión de Seguridad y Salud en el Trabajo',
    normativaBase: 'Decreto 1072 de 2015, Resolución 0312 de 2019',
    categoria: 'talento-humano',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Ministerio de Trabajo',
    responsable: 'Lucila Villamil Avendaño',
    area: 'Talento Humano',
    areaResponsable: 'Talento Humano',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/sst.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
  {
    codigo: 'INF-DENUNCIAS',
    nombre: 'Informe de Denuncias Recibidas',
    descripcion: 'Reporte semestral de denuncias por actos de corrupción o irregularidades',
    normativaBase: 'Ley 1474 de 2011 Estatuto Anticorrupción',
    categoria: 'transparencia',
    periodicidad: 'semestral',
    diaPresentacion: 30,
    entidadDestino: 'Secretaría de Transparencia',
    responsable: 'Sandra Paola Montero',
    area: 'Control Interno',
    areaResponsable: 'Control Interno',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/denuncias.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 15,
    activo: true,
  },
  {
    codigo: 'INF-DERECHOS-AUTOR',
    nombre: 'Informe de Uso de Software Licenciado',
    descripcion: 'Reporte anual de inventario y uso de software con licenciamiento',
    normativaBase: 'Ley 603 de 2000, Circular Externa 005 de 2002',
    categoria: 'administrativo',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Dirección Nacional de Derecho de Autor',
    responsable: 'Fernando Ávila',
    area: 'Gestión Tecnológica',
    areaResponsable: 'Gestión Tecnológica',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/derechos-autor.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
  {
    codigo: 'INF-PLAN-MEJORAMIENTO',
    nombre: 'Seguimiento Plan de Mejoramiento',
    descripcion: 'Informe trimestral de avance del Plan de Mejoramiento',
    normativaBase: 'Ley 42 de 1993, Resolución 0357 de 2008',
    categoria: 'control',
    periodicidad: 'trimestral',
    diaPresentacion: 15,
    entidadDestino: 'Contraloría y Entes de Control',
    responsable: 'Sandra Paola Montero',
    area: 'Control Interno',
    areaResponsable: 'Control Interno',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/plan-mejoramiento.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 10,
    activo: true,
  },
  {
    codigo: 'INF-INDICADORES',
    nombre: 'Informe de Indicadores de Gestión',
    descripcion: 'Reporte trimestral de indicadores estratégicos y de gestión',
    normativaBase: 'Decreto 1499 de 2017 MIPG',
    categoria: 'control',
    periodicidad: 'trimestral',
    diaPresentacion: 10,
    entidadDestino: 'Rectoría y Alta Dirección',
    responsable: 'Sandra Paola Montero',
    area: 'Planeación Estratégica',
    areaResponsable: 'Planeación Estratégica',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/indicadores.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 7,
    activo: true,
  },
  {
    codigo: 'INF-BIENES',
    nombre: 'Inventario de Bienes Muebles',
    descripcion: 'Actualización anual del inventario de bienes muebles de la entidad',
    normativaBase: 'Resolución 357 de 2008 CGN',
    categoria: 'administrativo',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Contaduría General de la Nación',
    responsable: 'Carlos Andrés Ruiz',
    area: 'Gestión Administrativa',
    areaResponsable: 'Gestión Administrativa',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/inventario-bienes.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
  {
    codigo: 'INF-CONFLICTOS-INTERES',
    nombre: 'Declaración de Conflictos de Interés',
    descripcion: 'Actualización anual de declaraciones de conflictos de interés de directivos',
    normativaBase: 'Ley 1437 de 2011, Ley 1474 de 2011',
    categoria: 'transparencia',
    periodicidad: 'anual',
    diaPresentacion: 31,
    entidadDestino: 'Secretaría General',
    responsable: 'Lucila Villamil Avendaño',
    area: 'Talento Humano',
    areaResponsable: 'Talento Humano',
    tienePlantilla: true,
    urlPlantilla: '/plantillas/conflictos-interes.xlsx',
    requiereAprobacion: true,
    diasAnticipacionAlerta: 30,
    activo: true,
  },
];

export async function seedInformesLey(dataSource: DataSource): Promise<void> {
  const repository = dataSource.getRepository(InformeLey);

  console.log('📊 Creando 20 Informes de Ley obligatorios...');

  for (const informeData of INFORMES_LEY_SEED) {
    const existente = await repository.findOne({ where: { codigo: informeData.codigo } });

    if (!existente) {
      const informe = repository.create(informeData);
      await repository.save(informe);
      console.log(`  ✅ Informe creado: ${informe.codigo} - ${informe.nombre}`);
    } else {
      console.log(`  ⏭️  Informe ya existe: ${informeData.codigo}`);
    }
  }

  console.log('  ✅ Informes de Ley completados\n');
}

