export enum Permissions {
  // Gestión Legal - Defensa Judicial
  GESTION_LEGAL_DEFENSA_JUDICIAL_MANAGE = 'gestion-legal.defensa-judicial.manage',
  GESTION_LEGAL_DEFENSA_JUDICIAL_CREATE = 'gestion-legal.defensa-judicial.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_DOC_UPLOAD = 'gestion-legal.defensa-judicial.expediente.doc.upload',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_DOC_DELETE = 'gestion-legal.defensa-judicial.expediente.doc.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_ACTUACION_CREATE = 'gestion-legal.defensa-judicial.expediente.actuacion.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_ACTUACION_DELETE = 'gestion-legal.defensa-judicial.expediente.actuacion.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_ACTUACION_AUDIENCIA_CREATE = 'gestion-legal.defensa-judicial.expediente.actuacion.audiencia.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_TAREA_CREATE = 'gestion-legal.defensa-judicial.expediente.tarea.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_TAREA_DELETE = 'gestion-legal.defensa-judicial.expediente.tarea.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_NOTA_CREATE = 'gestion-legal.defensa-judicial.expediente.nota.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EXPEDIENTE_NOTA_DELETE = 'gestion-legal.defensa-judicial.expediente.nota.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_AUTOS_CREATE = 'gestion-legal.defensa-judicial.autos.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_AUTOS_DELETE = 'gestion-legal.defensa-judicial.autos.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EVIDENCIAS_CREATE = 'gestion-legal.defensa-judicial.evidencias.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EVIDENCIAS_DELETE = 'gestion-legal.defensa-judicial.evidencias.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_EVIDENCIAS_ADMITIR = 'gestion-legal.defensa-judicial.evidencias.admitir',
  GESTION_LEGAL_DEFENSA_JUDICIAL_OFICIOS_CREATE = 'gestion-legal.defensa-judicial.oficios.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_OFICIOS_DELETE = 'gestion-legal.defensa-judicial.oficios.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_OFICIOS_ATENDER = 'gestion-legal.defensa-judicial.oficios.atender',
  GESTION_LEGAL_DEFENSA_JUDICIAL_ACTAS_CREATE = 'gestion-legal.defensa-judicial.actas.create',
  GESTION_LEGAL_DEFENSA_JUDICIAL_ACTAS_DELETE = 'gestion-legal.defensa-judicial.actas.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_ESTADOS_EDIT = 'gestion-legal.defensa-judicial.estados.edit',
  GESTION_LEGAL_DEFENSA_JUDICIAL_ABOGADO_REASIGNAR = 'gestion-legal.defensa-judicial.abogado.reasignar',
  GESTION_LEGAL_DEFENSA_JUDICIAL_AUDIENCIA_EDIT = 'gestion-legal.defensa-judicial.expediente.actuacion.audiencia.edit',
  GESTION_LEGAL_DEFENSA_JUDICIAL_AUDIENCIA_DELETE = 'gestion-legal.defensa-judicial.expediente.actuacion.audiencia.delete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_TAREA_EDIT = 'gestion-legal.defensa-judicial.expediente.tarea.edit',
  GESTION_LEGAL_DEFENSA_JUDICIAL_TAREA_COMPLETE = 'gestion-legal.defensa-judicial.expediente.tarea.complete',
  GESTION_LEGAL_DEFENSA_JUDICIAL_ARCHIVAR = 'gestion-legal.defensa-judicial.archivar',

  // Gestión Legal - Juzgamiento Disciplinario
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_MANAGE = 'gestion-legal.juzgamiento-disciplinario.manage',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_EDIT = 'gestion-legal.juzgamiento-disciplinario.expediente.edit',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_PRUEBA = 'gestion-legal.juzgamiento-disciplinario.expediente.prueba',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_DECISION = 'gestion-legal.juzgamiento-disciplinario.expediente.decision',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_EXCEPCION = 'gestion-legal.juzgamiento-disciplinario.expediente.excepcion',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_DECISION_NOTIFICAR = 'gestion-legal.juzgamiento-disciplinario.expediente.decision.notificar',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EXPEDIENTE_DOC_UPLOAD = 'gestion-legal.juzgamiento-disciplinario.expediente.doc.upload',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_AUTOS_CREATE = 'gestion-legal.juzgamiento-disciplinario.autos.create',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_AUTOS_DELETE = 'gestion-legal.juzgamiento-disciplinario.autos.delete',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EVIDENCIAS_CREATE = 'gestion-legal.juzgamiento-disciplinario.evidencias.create',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EVIDENCIAS_DELETE = 'gestion-legal.juzgamiento-disciplinario.evidencias.delete',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_EVIDENCIAS_ADMITIR = 'gestion-legal.juzgamiento-disciplinario.evidencias.admitir',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_OFICIOS_CREATE = 'gestion-legal.juzgamiento-disciplinario.oficios.create',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_OFICIOS_DELETE = 'gestion-legal.juzgamiento-disciplinario.oficios.delete',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_OFICIOS_ATENDER = 'gestion-legal.juzgamiento-disciplinario.oficios.atender',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_ACTAS_CREATE = 'gestion-legal.juzgamiento-disciplinario.actas.create',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_ACTAS_DELETE = 'gestion-legal.juzgamiento-disciplinario.actas.delete',
  GESTION_LEGAL_JUZGAMIENTO_DISCIPLINARIO_ESTADOS_EDIT = 'gestion-legal.juzgamiento-disciplinario.estados.edit',

  // Gestión Legal - Asesoría Jurídica
  GESTION_LEGAL_ASESORIA_JURIDICA_MANAGE = 'gestion-legal.asesoria-juridica.manage',
  GESTION_LEGAL_ASESORIA_JURIDICA_CREATE = 'gestion-legal.asesoria-juridica.create',
  GESTION_LEGAL_ASESORIA_JURIDICA_DELETE = 'gestion-legal.asesoria-juridica.delete',
  GESTION_LEGAL_ASESORIA_JURIDICA_EXPEDIENTE_DOC_UPLOAD = 'gestion-legal.asesoria-juridica.expediente.doc.upload',
  GESTION_LEGAL_ASESORIA_JURIDICA_EXPEDIENTE_DOC_DELETE = 'gestion-legal.asesoria-juridica.expediente.doc.delete',
  GESTION_LEGAL_ASESORIA_JURIDICA_ETAPA_EDIT = 'gestion-legal.asesoria-juridica.etapa.edit',
  GESTION_LEGAL_ASESORIA_JURIDICA_COMENTARIO_CREATE = 'gestion-legal.asesoria-juridica.comentario.create',
  GESTION_LEGAL_ASESORIA_JURIDICA_RESPONDER = 'gestion-legal.asesoria-juridica.responder',
  GESTION_LEGAL_ASESORIA_JURIDICA_APROBAR_RESPUESTA = 'gestion-legal.asesoria-juridica.aprobar-respuesta',
  GESTION_LEGAL_ASESORIA_JURIDICA_DEVOLVER_RESPUESTA = 'gestion-legal.asesoria-juridica.devolver-respuesta',

  // Gestión Legal - Centro de Comunicaciones
  GESTION_LEGAL_COMUNICACIONES_MANAGE = 'gestion-legal.comunicaciones.manage',
  GESTION_LEGAL_COMUNICACIONES_CREATE = 'gestion-legal.comunicaciones.create',
  GESTION_LEGAL_COMUNICACIONES_LEIDO = 'gestion-legal.comunicaciones.leido',
  GESTION_LEGAL_COMUNICACIONES_ARCHIVAR = 'gestion-legal.comunicaciones.archivar',

  // Gestión Legal - Términos e Informaciones
  GESTION_LEGAL_TERMINOS_MANAGE = 'gestion-legal.terminos.manage',

  // Gestión Legal - Órganos de Control
  GESTION_LEGAL_ORGANOS_CONTROL_MANAGE = 'gestion-legal.organos-control.manage',
  GESTION_LEGAL_ORGANOS_CONTROL_CREATE = 'gestion-legal.organos-control.create',
  GESTION_LEGAL_ORGANOS_CONTROL_ELABORAR = 'gestion-legal.organos-control.elaborar',
  GESTION_LEGAL_ORGANOS_CONTROL_DELETE = 'gestion-legal.organos-control.delete',
  GESTION_LEGAL_ORGANOS_CONTROL_DOC_UPLOAD = 'gestion-legal.organos-control.doc.upload',
  GESTION_LEGAL_ORGANOS_CONTROL_RESPUESTA_SEND = 'gestion-legal.organos-control.respuesta.send',
  GESTION_LEGAL_ORGANOS_CONTROL_RESPUESTA_ERASE = 'gestion-legal.organos-control.respuesta.erase',
  GESTION_LEGAL_ORGANOS_CONTROL_SOLICITAR_INSUMO = 'gestion-legal.organos-control.solicitar-insumo',
  GESTION_LEGAL_ORGANOS_CONTROL_ABOGADO_REASIGNAR = 'gestion-legal.organos-control.abogado.reasignar',

  // Gestión Legal - Procesos Coactivos
  GESTION_LEGAL_PROCESOS_COACTIVOS_MANAGE = 'gestion-legal.procesos-coactivos.manage',
  GESTION_LEGAL_PROCESOS_COACTIVOS_CREATE = 'gestion-legal.procesos-coactivos.create',
  GESTION_LEGAL_PROCESOS_COACTIVOS_EDIT = 'gestion-legal.procesos-coactivos.edit',
  GESTION_LEGAL_PROCESOS_COACTIVOS_DELETE = 'gestion-legal.procesos-coactivos.delete',

  // Gestión Legal - Expedientes Electrónicos
  GESTION_LEGAL_EXPEDIENTES_ELECTRONICOS_MANAGE = 'gestion-legal.expedientes-electronicos.manage',
  GESTION_LEGAL_EXPEDIENTES_ELECTRONICOS_UPLOAD = 'gestion-legal.expedientes-electronicos.upload',

  // Gestión Legal - Plan de Acción
  GESTION_LEGAL_PLAN_ACCION_MANAGE = 'gestion-legal.plan-accion.manage',
  GESTION_LEGAL_PLAN_ACCION_CREATE = 'gestion-legal.plan-accion.create',

  // Gestión Legal - Riesgos
  GESTION_LEGAL_RIESGOS_MANAGE = 'gestion-legal.riesgos.manage',
  GESTION_LEGAL_RIESGOS_CREATE = 'gestion-legal.riesgos.create',
  GESTION_LEGAL_RIESGOS_EDIT = 'gestion-legal.riesgos.edit',
  GESTION_LEGAL_RIESGOS_DELETE = 'gestion-legal.riesgos.delete',

  // Gestión Legal - Planes de Mejoramiento
  GESTION_LEGAL_PLANES_MEJORAMIENTO_MANAGE = 'gestion-legal.planes-mejoramiento.manage',
  GESTION_LEGAL_PLANES_MEJORAMIENTO_CREATE = 'gestion-legal.planes-mejoramiento.create',

  // Gestión Legal - Reportes
  GESTION_LEGAL_REPORTES_MANAGE = 'gestion-legal.reportes.manage',

  // Gestión Legal - Configuraciones
  GESTION_LEGAL_CONFIGURACIONES_MANAGE = 'gestion-legal.configuraciones.manage',
  GESTION_LEGAL_CONFIGURACIONES_CREATE = 'gestion-legal.configuraciones.create',
  GESTION_LEGAL_CONFIGURACIONES_EDIT = 'gestion-legal.configuraciones.edit',
  GESTION_LEGAL_CONFIGURACIONES_DELETE = 'gestion-legal.configuraciones.delete',

  // Registro Académico - Graduados
  GRADUATES_CREATE = 'graduates.create',
  GRADUATES_EDIT = 'graduates.edit',
  GRADUATES_VERIFY_CERTIFICATE = 'graduates.verify_certificate',
  GRADUATES_EXPORT = 'graduates.export',

  // Registro Académico - Certificados
  GRADUATES_CERTIFICATES_VIEW = 'graduates-certificates.certificates.view',
  GRADUATES_CERTIFICATES_EXPORT = 'graduates-certificates.certificates.export',
  GRADUATES_CERTIFICATES_EDIT = 'graduates-certificates.certificates.edit',
  GRADUATES_CERTIFICATES_REENVIAR = 'graduates-certificates.certificates.reenviar',
  GRADUATES_SOLICITUDE_VIEW = 'graduates-certificates.solicitude.view',
  GRADUATES_SOLICITUDE_REVIEW = 'graduates-certificates.solicitude.review',
  GRADUATES_SOLICITUDE_APROBAR = 'graduates-certificates.solicitude.aprobar',
  GRADUATES_SOLICITUDE_RECHAZAR = 'graduates-certificates.solicitude.rechazar',

  //Control Disciplinario - Procesos
  CONTROL_DISCIPLINARIO_PROCESOS_MANAGE = 'control-disciplinario.procesos.manage',
  CONTROL_DISCIPLINARIO_PROCESOS_CREATE = 'control-disciplinario.procesos.create',
  CONTROL_DISCIPLINARIO_PROCESOS_CONVERTIR = 'control-disciplinario.procesos.convertir',
  CONTROL_DISCIPLINARIO_PROCESOS_DEVOLVER = 'control-disciplinario.procesos.devolver',
  CONTROL_DISCIPLINARIO_PROCESOS_REDIMIR = 'control-disciplinario.procesos.redimir',
  CONTROL_DISCIPLINARIO_PROCESOS_ARCHIVAR = 'control-disciplinario.procesos.archivar',
  CONTROL_DISCIPLINARIO_PROCESOS_RESTAURAR = 'control-disciplinario.procesos.restaurar',
  CONTROL_DISCIPLINARIO_PROCESOS_EXPIDIENTE = 'control-disciplinario.procesos.expidiente',
  CONTROL_DISCIPLINARIO_PROCESOS_AUTOS_CREATE = 'control-disciplinario.procesos.autos.create',
  CONTROL_DISCIPLINARIO_PROCESOS_AUTOS_EDIT = 'control-disciplinario.procesos.autos.edit',
  CONTROL_DISCIPLINARIO_PROCESOS_AUTOS_DELETE = 'control-disciplinario.procesos.autos.delete',
  CONTROL_DISCIPLINARIO_PROCESOS_EVIDENCIA_CREATE = 'control-disciplinario.procesos.evidencia.create',
  CONTROL_DISCIPLINARIO_PROCESOS_EVIDENCIA_DELETE = 'control-disciplinario.procesos.evidencia.delete',
  CONTROL_DISCIPLINARIO_PROCESOS_EVIDENCIA_ADMITIR = 'control-disciplinario.procesos.evidencia.admitir',
  CONTROL_DISCIPLINARIO_PROCESOS_OFICIO_CREATE = 'control-disciplinario.procesos.oficio.create',
  CONTROL_DISCIPLINARIO_PROCESOS_OFICIO_DELETE = 'control-disciplinario.procesos.oficio.delete',
  CONTROL_DISCIPLINARIO_PROCESOS_ACTA_CREATE = 'control-disciplinario.procesos.acta.create',
  CONTROL_DISCIPLINARIO_PROCESOS_ACTA_DELETE = 'control-disciplinario.procesos.acta.delete',

  //Control Disciplinario - Noticias Disciplinarias
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_MANAGE = 'control-disciplinario.noticia-disciplinaria.manage',
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_EDIT = 'control-disciplinario.noticia-disciplinaria.edit',
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_DELETE = 'control-disciplinario.noticia-disciplinaria.delete',
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_ASIGNAR = 'control-disciplinario.noticia-disciplinaria.asignar',
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_DEVOLVER = 'control-disciplinario.noticia-disciplinaria.devolver',
  CONTROL_DISCIPLINARIO_NOTICIAS_DISCIPLINARIAS_REDIMIR = 'control-disciplinario.noticia-disciplinaria.redimir',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_VIEW = 'control-disciplinario.noticia-disciplinaria.view',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_VIEW_MINE = 'control-disciplinario.noticia-disciplinaria.view_mine',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_RESTAURAR = 'control-disciplinario.noticia-disciplinaria.restaurar',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_RESTAURAR_MINE = 'control-disciplinario.noticia-disciplinaria.restaurar_mine',

  //Control Disciplinario - Revisión y Aprobación
  CONTROL_DISCIPLINARIO_REVISION_APROBACION_MANAGE = 'control-disciplinario.revision-aprobacion.manage',
  CONTROL_DISCIPLINARIO_REVISION_APROBACION_DEVOLVER = 'control-disciplinario.revision-aprobacion.devolver',
  CONTROL_DISCIPLINARIO_REVISION_APROBACION_APROBAR = 'control-disciplinario.revision-aprobacion.aprobar',

  //Control Disciplinario - Expediente Electrónico
  CONTROL_DISCIPLINARIO_EXPIDENTE_ELECTRONICO_MANAGE = 'control-disciplinario.expediente-electronico.manage',
  CONTROL_DISCIPLINARIO_EXPIDENTE_ELECTRONICO_DOC_UPLOAD = 'control-disciplinario.expediente-electronico.doc.upload',

  //Control Disciplinario - Terminos y Alertas
  CONTROL_DISCIPLINARIO_TERMINOS_MANAGE = 'control-disciplinario.terminos.manage',
  CONTROL_DISCIPLINARIO_TERMINOS_TERMINO_CREATE = 'control-disciplinario.terminos.termino.create',
  CONTROL_DISCIPLINARIO_TERMINOS_TERMINO_FINISH = 'control-disciplinario.terminos.termino.finish',
  CONTROL_DISCIPLINARIO_TERMINOS_FESTIVO_CREATE = 'control-disciplinario.terminos.festivo.create',
  CONTROL_DISCIPLINARIO_TERMINOS_FESTIVO_EDIT = 'control-disciplinario.terminos.festivo.edit',
  CONTROL_DISCIPLINARIO_TERMINOS_FESTIVO_DELETE = 'control-disciplinario.terminos.festivo.delete',
  CONTROL_DISCIPLINARIO_TERMINOS_REGLA_EDIT = 'control-disciplinario.terminos.regla.edit',
  CONTROL_DISCIPLINARIO_TERMINOS_REGLA_DELETE = 'control-disciplinario.terminos.regla.delete',

  //Control Disciplinario - Profesionales
  CONTROL_DISCIPLINARIO_PROFESIONALES_MANAGE = 'control-disciplinario.profesionales.manage',
  CONTROL_DISCIPLINARIO_PROFESIONALES_CREATE = 'control-disciplinario.profesionales.create',
  CONTROL_DISCIPLINARIO_PROFESIONALES_EDIT = 'control-disciplinario.profesionales.edit',
  CONTROL_DISCIPLINARIO_PROFESIONALES_DELETE = 'control-disciplinario.profesionales.delete',
  
  //Control Disciplinario - Configuraciones
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_MANAGE = 'control-disciplinario.configuraciones.manage',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_EDIT = 'control-disciplinario.configuraciones.edit',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_RESET = 'control-disciplinario.configuraciones.reset',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_ETAPA_CREATE = 'control-disciplinario.configuraciones.etapa.create',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_ETAPA_EDIT = 'control-disciplinario.configuraciones.etapa.edit',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_ETAPA_DELETE = 'control-disciplinario.configuraciones.etapa.delete',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_CARGO_CREATE = 'control-disciplinario.configuraciones.cargo.create',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_CARGO_EDIT = 'control-disciplinario.configuraciones.cargo.edit',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_CARGO_DELETE = 'control-disciplinario.configuraciones.cargo.delete',
  CONTROL_DISCIPLINARIO_CONFIGURACIONES_FIRMA_UPLOAD = 'control-disciplinario.configuraciones.firma.upload',

  // Control Disciplinario - Nuevos Permisos (Granulares)
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_ALL = 'control-disciplinario.procesos.view_all',
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_MINE = 'control-disciplinario.procesos.view_mine',
  CONTROL_DISCIPLINARIO_PROCESOS_EDIT = 'control-disciplinario.procesos.edit',
  CONTROL_DISCIPLINARIO_PROCESOS_ASOCIAR = 'control-disciplinario.procesos.asociar',
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_DETAIL = 'control-disciplinario.procesos.view_detail',
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_GENERAL = 'control-disciplinario.procesos.view_general',
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_ARCHIVOS = 'control-disciplinario.procesos.view_archivos',
  CONTROL_DISCIPLINARIO_PROCESOS_ARCHIVOS_DOWNLOAD = 'control-disciplinario.procesos.archivos.download',
  CONTROL_DISCIPLINARIO_PROCESOS_ACTUACIONES_VIEW = 'control-disciplinario.procesos.actuaciones.view',
  CONTROL_DISCIPLINARIO_PROCESOS_ACTUACIONES_CREATE = 'control-disciplinario.procesos.actuaciones.create',
  CONTROL_DISCIPLINARIO_PROCESOS_TAREAS_VIEW = 'control-disciplinario.procesos.tareas.view',
  CONTROL_DISCIPLINARIO_PROCESOS_TAREAS_CREATE = 'control-disciplinario.procesos.tareas.create',
  CONTROL_DISCIPLINARIO_PROCESOS_NOTAS_VIEW = 'control-disciplinario.procesos.notas.view',
  CONTROL_DISCIPLINARIO_PROCESOS_NOTAS_CREATE = 'control-disciplinario.procesos.notas.create',
  CONTROL_DISCIPLINARIO_PROCESOS_NOTAS_DELETE = 'control-disciplinario.procesos.notas.delete',
  CONTROL_DISCIPLINARIO_PROCESOS_NOTES_DELETE = 'control-disciplinario.procesos.notas.delete',
  CONTROL_DISCIPLINARIO_PROCESOS_ASOCIAR_PROCESOS = 'control-disciplinario.procesos.asociar_procesos',
  CONTROL_DISCIPLINARIO_PROCESOS_REASIGNACION = 'control-disciplinario.procesos.reasignacion',
  CONTROL_DISCIPLINARIO_PROCESOS_REASSIGN = 'control-disciplinario.procesos.reasignacion',
  CONTROL_DISCIPLINARIO_PROCESOS_REASIGNACION_APPROVE = 'control-disciplinario.procesos.reasignacion.approve',
  CONTROL_DISCIPLINARIO_PROCESOS_REASIGNACION_INMEDIATA = 'control-disciplinario.procesos.reasignacion.inmediata',
  CONTROL_DISCIPLINARIO_PROCESOS_CREATE_PLIEGO = 'control-disciplinario.procesos.create_pliego',
  CONTROL_DISCIPLINARIO_PROCESOS_FILES_SEND_TO_REVIEW = 'control-disciplinario.procesos.files.send_to_review',
  CONTROL_DISCIPLINARIO_PROCESOS_SEND_TO_JURIDICA = 'control-disciplinario.procesos.send_to_juridica',
  CONTROL_DISCIPLINARIO_PROCESOS_FILES_UPLOAD = 'control-disciplinario.procesos.files.upload',
  CONTROL_DISCIPLINARIO_PROCESOS_TASKS_VIEW = 'control-disciplinario.procesos.tareas.view',
  CONTROL_DISCIPLINARIO_PROCESOS_TASKS_EDIT = 'control-disciplinario.procesos.tareas.edit',
  CONTROL_DISCIPLINARIO_PROCESOS_NOTES_VIEW = 'control-disciplinario.procesos.notas.view',
  CONTROL_DISCIPLINARIO_PROCESOS_KANBAN_MOVE = 'control-disciplinario.procesos.kanban.move',
  CONTROL_DISCIPLINARIO_PROCESOS_VIEW_LIST = 'control-disciplinario.procesos.view_list',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_VIEW_DETAIL = 'control-disciplinario.noticia-disciplinaria.view_detail',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_VIEW_DEVUELTAS = 'control-disciplinario.noticia-disciplinaria.view_devueltas',
  CONTROL_DISCIPLINARIO_NOTICIA_DISCIPLINARIA_VIEW_MIS_DEVUELTAS = 'control-disciplinario.noticia-disciplinaria.view_mis_devueltas',
  CONTROL_DISCIPLINARIO_REVISION_APROBACION_VIEW_DOCS = 'control-disciplinario.revision-aprobacion.view_docs',
  CONTROL_DISCIPLINARIO_REVISION_APROBACION_SEND_AUTO = 'control-disciplinario.revision-aprobacion.send_auto',
  CONTROL_DISCIPLINARIO_EXPEDIENTE_ELECTRONICO_VIEW_ALL = 'control-disciplinario.expediente-electronico.view_all',
  CONTROL_DISCIPLINARIO_EXPEDIENTE_ELECTRONICO_VIEW_DOC = 'control-disciplinario.expediente-electronico.view_doc',
  CONTROL_DISCIPLINARIO_EXPEDIENTE_ELECTRONICO_DOWNLOAD_DOC = 'control-disciplinario.expediente-electronico.download_doc',
  CONTROL_DISCIPLINARIO_EXPEDIENTE_ELECTRONICO_DOWNLOAD_HOJA_CONTROL = 'control-disciplinario.expediente-electronico.download_hoja_control',
  CONTROL_DISCIPLINARIO_EXPEDIENTE_ELECTRONICO_VIEW_HOJA_CONTROL = 'control-disciplinario.expediente-electronico.view_hoja_control',
  CONTROL_DISCIPLINARIO_TERMINOS_VIEW = 'control-disciplinario.terminos.view',
  CONTROL_DISCIPLINARIO_TERMINOS_VIEW_MINE = 'control-disciplinario.terminos.view_mine',
  CONTROL_DISCIPLINARIO_TERMINOS_VIEW_HISTORY = 'control-disciplinario.terminos.view_history',
  CONTROL_DISCIPLINARIO_TERMINOS_EXPORT_EXCEL = 'control-disciplinario.terminos.export_excel',
  CONTROL_DISCIPLINARIO_TERMINOS_EXPORT_PDF = 'control-disciplinario.terminos.export_pdf',
  CONTROL_DISCIPLINARIO_PROFESIONALES_VIEW = 'control-disciplinario.profesionales.view',
  CONTROL_DISCIPLINARIO_PROFESIONALES_VIEW_PROCESOS = 'control-disciplinario.profesionales.view_procesos',
  CONTROL_DISCIPLINARIO_CONFIG_KANBAN_EDIT_DIAS_ALERTAS = 'control-disciplinario.configuraciones.kanban.edit_dias_alertas',
  CONTROL_DISCIPLINARIO_CONFIG_KANBAN_ACTIVAR_ETAPA = 'control-disciplinario.configuraciones.kanban.activar_etapa',
  CONTROL_DISCIPLINARIO_CONFIG_KANBAN_GUARDAR = 'control-disciplinario.configuraciones.kanban.guardar',
  CONTROL_DISCIPLINARIO_CONFIG_CARGO_GUARDAR = 'control-disciplinario.configuraciones.cargo.guardar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_CAMBIAR_PLANTILLA = 'control-disciplinario.configuraciones.autos.cambiar_plantilla',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_EDITAR = 'control-disciplinario.configuraciones.autos.editar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_VER = 'control-disciplinario.configuraciones.autos.ver',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_ELIMINAR = 'control-disciplinario.configuraciones.autos.eliminar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_DESCARGAR = 'control-disciplinario.configuraciones.autos.descargar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_ACTIVAR = 'control-disciplinario.configuraciones.autos.activar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_PLANTILLA_AGREGAR = 'control-disciplinario.configuraciones.autos.plantilla.agregar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_PLANTILLA_ACTIVAR = 'control-disciplinario.configuraciones.autos.plantilla.activar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_PLANTILLA_DESCARGAR = 'control-disciplinario.configuraciones.autos.plantilla.descargar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_PLANTILLA_EDITAR = 'control-disciplinario.configuraciones.autos.plantilla.editar',
  CONTROL_DISCIPLINARIO_CONFIG_AUTOS_PLANTILLA_ELIMINAR = 'control-disciplinario.configuraciones.autos.plantilla.eliminar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_CAMBIAR_PLANTILLA = 'control-disciplinario.configuraciones.oficios.cambiar_plantilla',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_EDITAR = 'control-disciplinario.configuraciones.oficios.editar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_VER = 'control-disciplinario.configuraciones.oficios.ver',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_ELIMINAR = 'control-disciplinario.configuraciones.oficios.eliminar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_DESCARGAR = 'control-disciplinario.configuraciones.oficios.descargar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_ACTIVAR = 'control-disciplinario.configuraciones.oficios.activar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_PLANTILLA_AGREGAR = 'control-disciplinario.configuraciones.oficios.plantilla.agregar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_PLANTILLA_ACTIVAR = 'control-disciplinario.configuraciones.oficios.plantilla.activar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_PLANTILLA_DESCARGAR = 'control-disciplinario.configuraciones.oficios.plantilla.descargar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_PLANTILLA_EDITAR = 'control-disciplinario.configuraciones.oficios.plantilla.editar',
  CONTROL_DISCIPLINARIO_CONFIG_OFICIOS_PLANTILLA_ELIMINAR = 'control-disciplinario.configuraciones.oficios.plantilla.eliminar',
  CONTROL_DISCIPLINARIO_CONFIG_ENTIDADES_CREATE = 'control-disciplinario.configuraciones.entidades.create',
  CONTROL_DISCIPLINARIO_CONFIG_ENTIDADES_ACTIVAR = 'control-disciplinario.configuraciones.entidades.activar',
  CONTROL_DISCIPLINARIO_CONFIG_ENTIDADES_EDIT = 'control-disciplinario.configuraciones.entidades.edit',
  CONTROL_DISCIPLINARIO_CONFIG_ENTIDADES_DELETE = 'control-disciplinario.configuraciones.entidades.delete',
  CONTROL_DISCIPLINARIO_CONFIG_NOTIFICACIONES_SISTEMA = 'control-disciplinario.configuraciones.notificaciones.sistema',
  CONTROL_DISCIPLINARIO_CONFIG_NOTIFICACIONES_SEMAFORO = 'control-disciplinario.configuraciones.notificaciones.semaforo',
  CONTROL_DISCIPLINARIO_CONFIG_NOTIFICACIONES_GUARDAR = 'control-disciplinario.configuraciones.notificaciones.guardar',
  CONTROL_DISCIPLINARIO_CONFIG_PRESCRIPCION_EDIT = 'control-disciplinario.configuraciones.prescripcion.edit',
  CONTROL_DISCIPLINARIO_CONFIG_PRESCRIPCION_GUARDAR = 'control-disciplinario.configuraciones.prescripcion.guardar',

  //--------------------------------------------------------------------------------------------------------------------------

  // Auditoría OCIG
  CONTROL_INTERNO_AUDITORIA_MANAGE = 'control-interno.auditoria.manage',
  CONTROL_INTERNO_AUDITORIA_VIEW = 'control-interno.auditoria.view',
  CONTROL_INTERNO_AUDITORIA_CREATE = 'control-interno.auditoria.create',
  CONTROL_INTERNO_AUDITORIA_EDIT = 'control-interno.auditoria.edit',
  CONTROL_INTERNO_AUDITORIA_ADD_AMPLIACION = 'control-interno.auditoria.add.ampliacion',
  CONTROL_INTERNO_AUDITORIA_STATE_CHANGE = 'control-interno.auditoria.state.change',
  CONTROL_INTERNO_AUDITORIA_AUDIT = 'control-interno.auditoria.audit',
  CONTROL_INTERNO_AUDITORIA_APPROVE = 'control-interno.auditoria.approve',
  CONTROL_INTERNO_AUDITORIA_EXPORT = 'control-interno.auditoria.export',
  CONTROL_INTERNO_AUDITORIA_ARCHIVE = 'control-interno.auditoria.archive',
  CONTROL_INTERNO_AUDITORIA_DELETE = 'control-interno.auditoria.delete',
  CONTROL_INTERNO_AUDITORIA_NOTAS_CREATE = 'control-interno.auditoria.notas.create',
  CONTROL_INTERNO_AUDITORIA_NOTAS_DELETE = 'control-interno.auditoria.notas.delete',

  // Hallazgos OCIG
  CONTROL_INTERNO_HALLAZGOS_MANAGE = 'control-interno.hallazgos.manage',
  CONTROL_INTERNO_HALLAZGOS_VIEW = 'control-interno.hallazgos.view',
  CONTROL_INTERNO_HALLAZGOS_CREATE = 'control-interno.hallazgos.create',
  CONTROL_INTERNO_HALLAZGOS_EDIT = 'control-interno.hallazgos.edit',
  CONTROL_INTERNO_HALLAZGOS_DELETE = 'control-interno.hallazgos.delete',
  CONTROL_INTERNO_HALLAZGOS_APPROVE = 'control-interno.hallazgos.approve',

  // Evidencias OCIG
  CONTROL_INTERNO_EVIDENCIAS_VIEW = 'control-interno.evidencias.view',
  CONTROL_INTERNO_EVIDENCIAS_CREATE = 'control-interno.evidencias.create',
  CONTROL_INTERNO_EVIDENCIAS_DELETE = 'control-interno.evidencias.delete',
  CONTROL_INTERNO_EVIDENCIAS_VALIDATE = 'control-interno.evidencias.validate',

  // Aprobaciones OCIG
  CONTROL_INTERNO_APROBACIONES_VIEW = 'control-interno.aprobaciones.view',
  CONTROL_INTERNO_APROBACIONES_CREATE = 'control-interno.aprobaciones.create',
  CONTROL_INTERNO_APROBACIONES_EDIT = 'control-interno.aprobaciones.edit',
  CONTROL_INTERNO_APROBACIONES_DELETE = 'control-interno.aprobaciones.delete',

  // Documentos OCIG
  CONTROL_INTERNO_DOCUMENTOS_VIEW = 'control-interno.documentos.view',
  CONTROL_INTERNO_DOCUMENTOS_CREATE = 'control-interno.documentos.create',
  CONTROL_INTERNO_DOCUMENTOS_EDIT = 'control-interno.documentos.edit',
  CONTROL_INTERNO_DOCUMENTOS_DELETE = 'control-interno.documentos.delete',

  // Planeación OCIG
  CONTROL_INTERNO_PLANEACION_MANAGE = 'control-interno.planeacion.manage',
  CONTROL_INTERNO_PLANEACION_CREATE = 'control-interno.planeacion.create',
  CONTROL_INTERNO_PLANEACION_AREA_CREATE = 'control-interno.planeacion.area.create',
  CONTROL_INTERNO_PLANEACION_AREA_STATE_CHANGE = 'control-interno.planeacion.area.state.change',
  CONTROL_INTERNO_PLANEACION_AREA_EDIT = 'control-interno.planeacion.area.edit',
  CONTROL_INTERNO_PLANEACION_PLAN_CREATE = 'control-interno.planeacion.plan.create',
  CONTROL_INTERNO_PLANEACION_PLAN_EDIT = 'control-interno.planeacion.plan.edit',

  // Plan Anual 5 Roles (Decreto 648/2017)
  CONTROL_INTERNO_PLAN_ANUAL_VIEW = 'control-interno.plan-anual.view',
  CONTROL_INTERNO_PLAN_ANUAL_CREATE = 'control-interno.plan-anual.create',
  CONTROL_INTERNO_PLAN_ANUAL_EDIT = 'control-interno.plan-anual.edit',
  CONTROL_INTERNO_PLAN_ANUAL_DELETE = 'control-interno.plan-anual.delete',
  CONTROL_INTERNO_PLAN_ANUAL_APPROVE = 'control-interno.plan-anual.approve',
  CONTROL_INTERNO_PLAN_ANUAL_ACTIVATE = 'control-interno.plan-anual.activate',
  CONTROL_INTERNO_PLAN_ANUAL_EXPORT = 'control-interno.plan-anual.export',
  CONTROL_INTERNO_PLAN_ANUAL_ASSIGN = 'control-interno.plan-anual.assign',
  CONTROL_INTERNO_PLAN_ANUAL_FOLLOW_UP = 'control-interno.plan-anual.follow-up',

  // Planes de Mejoramiento
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_MANAGE = 'control-interno.planes-mejoramiento.manage',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_VIEW = 'control-interno.planes-mejoramiento.view',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_CREATE = 'control-interno.planes-mejoramiento.create',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_EDIT = 'control-interno.planes-mejoramiento.edit',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_DELETE = 'control-interno.planes-mejoramiento.delete',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_APPROVE = 'control-interno.planes-mejoramiento.approve',
  CONTROL_INTERNO_PLANES_MEJORAMIENTO_FOLLOW_UP = 'control-interno.planes-mejoramiento.follow-up',

  // Informes de Ley
  CONTROL_INTERNO_INFORMES_DE_LEY_MANAGE = 'control-interno.informes-de-ley.manage',
  CONTROL_INTERNO_INFORMES_DE_LEY_VIEW = 'control-interno.informes-de-ley.view',
  CONTROL_INTERNO_INFORMES_DE_LEY_CREATE = 'control-interno.informes-de-ley.create',
  CONTROL_INTERNO_INFORMES_DE_LEY_EDIT = 'control-interno.informes-de-ley.edit',
  CONTROL_INTERNO_INFORMES_DE_LEY_DELETE = 'control-interno.informes-de-ley.delete',
  CONTROL_INTERNO_INFORMES_DE_LEY_APPROVE = 'control-interno.informes-de-ley.approve',
  CONTROL_INTERNO_INFORMES_DE_LEY_GENERATE = 'control-interno.informes-de-ley.generate',
  CONTROL_INTERNO_INFORMES_DE_LEY_EXPORT = 'control-interno.informes-de-ley.export',

  // Expidientes
  CONTROL_INTERNO_EXPEDIENTES_MANAGE = 'control-interno.expedientes.manage',
  CONTROL_INTERNO_EXPEDIENTES_UPLOAD = 'control-interno.expedientes.upload',

  // Biblioteca / Listas de Chequeo
  CONTROL_INTERNO_LISTAS_CHEQUEO_VIEW = 'control-interno.listas-chequeo.view',
  CONTROL_INTERNO_LISTAS_CHEQUEO_CREATE = 'control-interno.listas-chequeo.create',
  CONTROL_INTERNO_LISTAS_CHEQUEO_EDIT = 'control-interno.listas-chequeo.edit',
  CONTROL_INTERNO_LISTAS_CHEQUEO_DELETE = 'control-interno.listas-chequeo.delete',
  CONTROL_INTERNO_LISTAS_CHEQUEO_APPLY = 'control-interno.listas-chequeo.apply',
  CONTROL_INTERNO_LISTAS_CHEQUEO_EXPORT = 'control-interno.listas-chequeo.export',

  // Configuraciones
  CONTROL_INTERNO_CONFIGURACIONES_MANAGE = 'control-interno.configuraciones.manage',
  CONTROL_INTERNO_CONFIGURACIONES_CONFIG_AUDIT_TIPO_CREATE = 'control-interno.configuraciones.config-audit.tipo.create',
  CONTROL_INTERNO_CONFIGURACIONES_CONFIG_AUDIT_LISTA_CREATE = 'control-interno.configuraciones.config-audit.lista.create',
  CONTROL_INTERNO_CONFIGURACIONES_KANBAN_CREATE = 'control-interno.configuraciones.kanban.create',
  CONTROL_INTERNO_CONFIGURACIONES_KANBAN_AUDIT_EDIT = 'control-interno.configuraciones.kanban.audit.edit',
  CONTROL_INTERNO_CONFIGURACIONES_KANBAN_AUDIT_DELETE = 'control-interno.configuraciones.kanban.audit.delete',
  CONTROL_INTERNO_CONFIGURACIONES_KANBAN_PLAN_EDIT = 'control-interno.configuraciones.kanban.plan.edit',
  CONTROL_INTERNO_CONFIGURACIONES_KANBAN_PLAN_DELETE = 'control-interno.configuraciones.kanban.plan.delete',
  // Registro Único Nacional Docente (RUND)
  BANCO_DOCENTES_RUND_MANAGE = 'banco-docentes.rund.manage',
  BANCO_DOCENTES_RUND_VIEW = 'banco-docentes.rund.view',
  BANCO_DOCENTES_RUND_EDIT = 'banco-docentes.rund.edit',
  BANCO_DOCENTES_RUND_VALIDATE = 'banco-docentes.rund.validate',
  BANCO_DOCENTES_RUND_IMPORT = 'banco-docentes.rund.import',
  BANCO_DOCENTES_RUND_EXPORT = 'banco-docentes.rund.export',
  BANCO_DOCENTES_RUND_INVITE = 'banco-docentes.rund.invite',

  // Programación Académica (PTA)
  PTA_PROGRAMACION_ACADEMICA_MANAGE = 'pta.programacion-academica.manage',
  PTA_PROGRAMACION_ACADEMICA_OFERTA_VIEW = 'pta.programacion-academica.oferta.view',
  PTA_PROGRAMACION_ACADEMICA_OFERTA_EDIT = 'pta.programacion-academica.oferta.edit',
  PTA_PROGRAMACION_ACADEMICA_ASIGNACION_MANAGE = 'pta.programacion-academica.asignacion.manage',
  PTA_PROGRAMACION_ACADEMICA_PRECARGA_MANAGE = 'pta.programacion-academica.precarga.manage',
  PTA_PROGRAMACION_ACADEMICA_NOTIFICAR = 'pta.programacion-academica.notificar',

  // Estructura Organizacional
  ESTRUCTURA_ORGANIZACIONAL_MANAGE = 'estructura-organizacional.manage',
  ESTRUCTURA_ORGANIZACIONAL_VIEW = 'estructura-organizacional.view',
  ESTRUCTURA_ORGANIZACIONAL_NODE_CREATE = 'estructura-organizacional.node.create',
  ESTRUCTURA_ORGANIZACIONAL_NODE_EDIT = 'estructura-organizacional.node.edit',
  ESTRUCTURA_ORGANIZACIONAL_NODE_DELETE = 'estructura-organizacional.node.delete',
  ESTRUCTURA_ORGANIZACIONAL_IMPORT = 'estructura-organizacional.import',
  ESTRUCTURA_ORGANIZACIONAL_EXPORT = 'estructura-organizacional.export',
}
