version: '3.8'

services:
  # FRONTEND
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-frontend:dev-latest

  # BACKEND MICROSERVICES
  api-gateway:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-api-gateway:dev-latest
  auth-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-auth-service:dev-latest
  academic-registration-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-academic-registration-service:dev-latest
  academic-work-plan-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-academic-work-plan-service:dev-latest
  certification-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-certification-service:dev-latest
  internal-disciplinary-control-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-internal-disciplinary-control-service:dev-latest
  interoperability-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-interoperability-service:dev-latest
  internal-institutional-control-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-internal-institutional-control-service:dev-latest
  legal-management-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-legal-management-service:dev-latest
  notifications-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-notifications-service:dev-latest
  travel-expenses-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-travel-expenses-service:dev-latest
  audit-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-hernan-saroa}/esap-audit-service:dev-latest
