FROM nginx:alpine

COPY nginx.frontend.static.conf /etc/nginx/conf.d/default.conf

ARG FRONTEND_PREBUILT_DIST_DIR
RUN test -n "${FRONTEND_PREBUILT_DIST_DIR}"

COPY ${FRONTEND_PREBUILT_DIST_DIR} /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
