FROM nginx:alpine

COPY docker/nginx/nginx.main.conf /etc/nginx/nginx.conf

RUN mkdir -p /opt/esap-nginx
COPY nginx.frontend.gateway.conf /opt/esap-nginx/http.conf
COPY nginx.frontend.gateway.tls.conf.template /opt/esap-nginx/tls.conf.template
COPY docker/nginx/40-esap-select-config.sh /docker-entrypoint.d/40-esap-select-config.sh
RUN chmod +x /docker-entrypoint.d/40-esap-select-config.sh

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
