/**
 * ============================================
 * DATOS MOCK PARA SIGL
 * ============================================
 * 
 * Datos de prueba centralizados con casos realistas para testing con cliente
 * Incluye casos representativos de los 11 módulos del Sistema Integral de Gestión Legal
 */

import {
  Scale,
  Shield,
  FileQuestion,
  Gavel,
  DollarSign,
  Mail,
  MessageSquare,
  Target,
  AlertTriangle,
  TrendingUp,
  Calendar,
} from 'lucide-react';

// ============================================
// USUARIOS
// ============================================

export const USUARIOS_MOCK = [
  { id: 'u1', nombre: 'Carlos Méndez', rol: 'jefe' as const, iniciales: 'CM', color: '#003DA5' },
  { id: 'u2', nombre: 'Ana García', rol: 'coordinador' as const, iniciales: 'AG', color: '#0066CC' },
  { id: 'u3', nombre: 'Luis Rodríguez', rol: 'abogado' as const, iniciales: 'LR', color: '#4A90E2' },
  { id: 'u4', nombre: 'María Pérez', rol: 'abogado' as const, iniciales: 'MP', color: '#7B68EE' },
  { id: 'u5', nombre: 'Pedro Sánchez', rol: 'auxiliar' as const, iniciales: 'PS', color: '#20B2AA' },
  { id: 'u6', nombre: 'Laura Martínez', rol: 'abogado' as const, iniciales: 'LM', color: '#8B5CF6' },
  { id: 'u7', nombre: 'Jorge Torres', rol: 'abogado' as const, iniciales: 'JT', color: '#EC4899' },
  { id: 'u8', nombre: 'Sandra Gómez', rol: 'coordinador' as const, iniciales: 'SG', color: '#10B981' },
];

// ============================================
// CASOS - DEFENSA JUDICIAL (MOD-01)
// ============================================

const CASOS_DEFENSA_JUDICIAL = [
  {
    id: 'dj-001',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00234',
    asunto: 'Acción de Tutela - Derecho Fundamental a la Educación',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[2],
    colaboradores: [
      { id: 'u4', nombre: 'María Pérez', iniciales: 'MP', color: '#7B68EE' },
      { id: 'u5', nombre: 'Pedro Sánchez', iniciales: 'PS', color: '#20B2AA' },
    ],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2024-12-20'),
    diasRestantes: 2,
    progreso: 65,
    proximaAccion: 'Presentar escrito de contestación',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 3 horas - Se recibió notificación del juzgado',
    descripcionCompleta: 'Acción de tutela presentada por estudiante contra la ESAP por presunta vulneración del derecho a la educación. Jurisdicción Constitucional.',
    entidadDemandante: 'Juan Pérez Gómez',
    numeroJuzgado: 'Juzgado 25 Civil Municipal de Bogotá',
    pretensiones: 'Ordene a la ESAP readmitir al estudiante y permitirle continuar con sus estudios',
    cuantia: 'Indeterminada',
    etiquetas: ['Urgente', 'Tutela', 'Constitucional'],
    comentarios: 5,
    documentos: 8,
  },
  {
    id: 'dj-002',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00567',
    asunto: 'Demanda Laboral - Reintegro y Pago de Salarios',
    estado: 'inicial' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[1],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-17'),
    fechaVencimiento: new Date('2025-01-27'),
    diasRestantes: 40,
    progreso: 5,
    proximaAccion: 'Asignar abogado responsable y solicitar documentación',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 día - Demanda notificada por el Juzgado Laboral',
    descripcionCompleta: 'Demanda laboral de reintegro y pago de salarios presentada por ex-funcionario. Jurisdicción Laboral.',
    entidadDemandante: 'Roberto Suárez Díaz',
    numeroJuzgado: 'Juzgado 12 Laboral del Circuito de Bogotá',
    pretensiones: 'Reintegro al cargo, pago de salarios dejados de percibir y reconocimiento de prestaciones sociales',
    cuantia: '$45.000.000',
    etiquetas: ['Laboral', 'Nuevo', 'Reintegro'],
    comentarios: 0,
    documentos: 4,
  },
  {
    id: 'dj-003',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00345',
    asunto: 'Acción Popular - Transparencia en Contratación',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-14'),
    fechaVencimiento: new Date('2025-01-15'),
    diasRestantes: 28,
    progreso: 25,
    proximaAccion: 'Iniciar contestación de la demanda',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 4 días - Asignado a María Pérez',
    descripcionCompleta: 'Acción popular sobre transparencia en procesos de contratación. Jurisdicción Contencioso Administrativa.',
    entidadDemandante: 'Fundación Transparencia Colombia',
    numeroJuzgado: 'Juzgado 5° Administrativo de Bogotá',
    pretensiones: 'Declarar vulneración de derechos colectivos y ordenar publicación de contratos',
    cuantia: 'Indeterminada',
    etiquetas: ['Popular', 'Contratación', 'Transparencia'],
    comentarios: 2,
    documentos: 5,
  },
  {
    id: 'dj-004',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00987',
    asunto: 'Demanda Contractual - Incumplimiento de Convenio Interadministrativo',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
    ],
    creador: USUARIOS_MOCK[3],
    fechaCreacion: new Date('2024-12-08'),
    fechaVencimiento: new Date('2024-12-23'),
    diasRestantes: 5,
    progreso: 75,
    proximaAccion: 'Revisar propuesta de contestación antes de radicación',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 horas - Borrador de respuesta cargado para revisión',
    descripcionCompleta: 'Demanda contractual por presunto incumplimiento de convenio interadministrativo con universidad pública. Jurisdicción Ordinaria.',
    entidadDemandante: 'Universidad Pública del Caribe',
    numeroJuzgado: 'Juzgado 18 Civil del Circuito',
    pretensiones: 'Resolución del convenio y pago de perjuicios',
    cuantia: '$120.000.000',
    etiquetas: ['Contractual', 'Revisión', 'Convenio'],
    comentarios: 6,
    documentos: 14,
  },
  {
    id: 'dj-005',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00654',
    asunto: 'Nulidad y Restablecimiento - Acto Administrativo Resolución 234/2024',
    estado: 'en_proceso' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-11-28'),
    fechaVencimiento: new Date('2025-01-05'),
    diasRestantes: 18,
    progreso: 60,
    proximaAccion: 'Preparar alegatos de conclusión',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 semana - Etapa probatoria cerrada',
    descripcionCompleta: 'Acción de nulidad y restablecimiento del derecho contra acto administrativo de cierre de programa académico. Jurisdicción Contencioso Administrativa.',
    entidadDemandante: 'Asociación de Egresados ESAP',
    numeroJuzgado: 'Juzgado 8° Administrativo de Bogotá',
    pretensiones: 'Nulidad de Resolución 234/2024 y restablecimiento de programa académico',
    cuantia: 'Indeterminada',
    etiquetas: ['Nulidad', 'Administrativo', 'Académico'],
    comentarios: 8,
    documentos: 18,
  },
  {
    id: 'dj-006',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00321',
    asunto: 'Tutela - Derecho de Petición en Interés General',
    estado: 'pendiente_aprobacion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[2],
    colaboradores: [
      { id: 'u4', nombre: 'María Pérez', iniciales: 'MP', color: '#7B68EE' },
    ],
    creador: USUARIOS_MOCK[3],
    fechaCreacion: new Date('2024-12-16'),
    fechaVencimiento: new Date('2024-12-19'),
    diasRestantes: 1,
    progreso: 90,
    proximaAccion: 'Aprobar respuesta para envío urgente (PLAZO CRÍTICO)',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 30 min - Respuesta lista, requiere firma del Jefe OJ',
    descripcionCompleta: 'Acción de tutela por presunta vulneración del derecho de petición. Plazo: 10 días hábiles. Jurisdicción Constitucional.',
    entidadDemandante: 'Consejo Estudiantil ESAP Nacional',
    numeroJuzgado: 'Juzgado 33 Civil Municipal de Bogotá',
    pretensiones: 'Ordenar respuesta de fondo a petición radicada hace 45 días',
    cuantia: 'Indeterminada',
    etiquetas: ['Tutela', 'Urgente', 'Aprobación', '10 días'],
    comentarios: 4,
    documentos: 6,
  },
  {
    id: 'dj-007',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00189',
    asunto: 'Reparación Directa - Daño Antijurídico por Falla del Servicio',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-11-15'),
    fechaVencimiento: new Date('2024-12-10'),
    diasRestantes: -8,
    progreso: 100,
    proximaAccion: 'Archivo - Proceso finalizado con sentencia favorable',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 8 días - Sentencia favorable radicada y ejecutoriada',
    descripcionCompleta: 'Demanda de reparación directa por daño antijurídico. Caso cerrado con sentencia favorable a la ESAP. Jurisdicción Contencioso Administrativa.',
    entidadDemandante: 'Comerciante afectado por obra pública',
    numeroJuzgado: 'Tribunal Administrativo de Cundinamarca',
    pretensiones: 'Pago de perjuicios materiales e inmateriales',
    cuantia: '$85.000.000',
    etiquetas: ['Completado', 'Sentencia', 'Favorable'],
    comentarios: 12,
    documentos: 25,
  },
  {
    id: 'dj-008',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00112',
    asunto: 'Acción de Cumplimiento - Decreto 1083 de 2015',
    estado: 'en_espera' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2025-01-10'),
    diasRestantes: 23,
    progreso: 40,
    proximaAccion: 'Esperar auto de pruebas del juzgado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Contestación radicada exitosamente',
    descripcionCompleta: 'Acción de cumplimiento para exigir aplicación de normas sobre contratación pública. Jurisdicción Contencioso Administrativa.',
    entidadDemandante: 'Veeduría Ciudadana Territorial',
    numeroJuzgado: 'Juzgado 14 Administrativo de Bogotá',
    pretensiones: 'Cumplimiento del Decreto 1083 de 2015 en contratación',
    cuantia: 'Indeterminada',
    etiquetas: ['Cumplimiento', 'Veeduría', 'Contratación'],
    comentarios: 3,
    documentos: 9,
  },
  {
    id: 'dj-009',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2024-00445',
    asunto: 'Demanda Ejecutiva - Cobro de Obligaciones Contractuales',
    estado: 'vencido' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-11-20'),
    fechaVencimiento: new Date('2024-12-15'),
    diasRestantes: -3,
    progreso: 30,
    proximaAccion: '¡VENCIDO! Presentar excepciones de fondo urgentemente',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 4 días - PLAZO VENCIDO sin respuesta',
    descripcionCompleta: 'Proceso ejecutivo de cobro por obligaciones contractuales. PLAZO VENCIDO. Jurisdicción Ordinaria.',
    entidadDemandante: 'Empresa Constructora XYZ S.A.S.',
    numeroJuzgado: 'Juzgado 22 Civil Municipal',
    pretensiones: 'Cobro ejecutivo de saldo adeudado por contrato',
    cuantia: '$68.500.000',
    etiquetas: ['Vencido', 'Urgente', 'Ejecutivo'],
    comentarios: 9,
    documentos: 11,
  },
  {
    id: 'dj-010',
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    radicado: 'PJ-2025-00001',
    asunto: 'Nulidad Electoral - Elección de Representantes Estudiantiles',
    estado: 'inicial' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-18'),
    fechaVencimiento: new Date('2025-01-22'),
    diasRestantes: 35,
    progreso: 10,
    proximaAccion: 'Revisión inicial y asignación de abogado sustanciador',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 12 horas - Notificación recibida',
    descripcionCompleta: 'Acción de nulidad electoral contra proceso de elección de representantes estudiantiles. Jurisdicción Contencioso Administrativa.',
    entidadDemandante: 'Candidato no electo',
    numeroJuzgado: 'Juzgado 11 Administrativo de Bogotá',
    pretensiones: 'Nulidad del proceso electoral y nueva convocatoria',
    cuantia: 'Indeterminada',
    etiquetas: ['Electoral', 'Nuevo', 'Estudiantes'],
    comentarios: 1,
    documentos: 3,
  },
];

// ============================================
// CASOS - ÓRGANOS DE CONTROL (MOD-02)
// ============================================

const CASOS_ORGANOS_CONTROL = [
  {
    id: 'oc-001',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'CGR-2024-00567',
    asunto: 'Requerimiento Contraloría General - Contratación 2023',
    estado: 'pendiente_aprobacion' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
    ],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2024-12-22'),
    diasRestantes: 4,
    progreso: 85,
    proximaAccion: 'Aprobar respuesta antes de envío a CGR',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 hora - Borrador de respuesta completado',
    descripcionCompleta: 'Requerimiento de información sobre procesos de contratación del año 2023. Plazo: 30 días hábiles.',
    etiquetas: ['CGR', 'Contratación', 'Urgente'],
    comentarios: 3,
    documentos: 12,
  },
  {
    id: 'oc-002',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'PROC-2024-00234',
    asunto: 'Requerimiento Procuraduría - Investigación Disciplinaria',
    estado: 'en_proceso' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[2],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
      { id: 'u4', nombre: 'María Pérez', iniciales: 'MP', color: '#7B68EE' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-12'),
    fechaVencimiento: new Date('2024-12-27'),
    diasRestantes: 9,
    progreso: 50,
    proximaAccion: 'Recopilar documentación de archivo central',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 5 horas - Procuraduría amplió solicitud',
    descripcionCompleta: 'Requerimiento de información para investigación disciplinaria. Plazo: 20 días hábiles.',
    etiquetas: ['Procuraduría', 'Disciplinaria', 'Información'],
    comentarios: 7,
    documentos: 8,
  },
  {
    id: 'oc-003',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'DEF-2024-00089',
    asunto: 'Requerimiento Defensoría del Pueblo - Derechos Estudiantiles',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-16'),
    fechaVencimiento: new Date('2024-12-31'),
    diasRestantes: 13,
    progreso: 20,
    proximaAccion: 'Solicitar información a Vicerrectoría Académica',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Caso asignado a Jorge Torres',
    descripcionCompleta: 'Solicitud de información sobre políticas de garantía de derechos estudiantiles. Plazo: 15 días hábiles.',
    etiquetas: ['Defensoría', 'Estudiantes', 'Políticas'],
    comentarios: 2,
    documentos: 4,
  },
  {
    id: 'oc-004',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'DANE-2024-00156',
    asunto: 'Requerimiento DANE - Información Estadística Institucional',
    estado: 'en_revision' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-12-08'),
    fechaVencimiento: new Date('2025-01-12'),
    diasRestantes: 25,
    progreso: 70,
    proximaAccion: 'Revisar consolidado de cifras institucionales',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Ayer - Planeación envió información preliminar',
    descripcionCompleta: 'Solicitud de información estadística sobre matrícula, docentes y programas académicos. Plazo: 30 días hábiles.',
    etiquetas: ['DANE', 'Estadística', 'Información'],
    comentarios: 4,
    documentos: 15,
  },
  {
    id: 'oc-005',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'CGR-2024-00723',
    asunto: 'Requerimiento CGR - Ajuste de Información Contable',
    estado: 'requiere_accion' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-14'),
    fechaVencimiento: new Date('2024-12-21'),
    diasRestantes: 3,
    progreso: 40,
    proximaAccion: 'Coordinar con Dirección Financiera para ajustes urgentes',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 3 horas - CGR detectó inconsistencias',
    descripcionCompleta: 'Requerimiento de ajuste sobre información contable previamente enviada. Plazo reducido: 10 días hábiles.',
    etiquetas: ['CGR', 'Ajuste', 'Contabilidad', 'Urgente'],
    comentarios: 5,
    documentos: 9,
  },
  {
    id: 'oc-006',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'MIN-2024-00412',
    asunto: 'Requerimiento MinEducación - Registro Calificado',
    estado: 'inicial' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[1],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-17'),
    fechaVencimiento: new Date('2025-01-20'),
    diasRestantes: 34,
    progreso: 5,
    proximaAccion: 'Convocar comité de autoevaluación',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 día - Notificación recibida',
    descripcionCompleta: 'Solicitud de documentación para renovación de registro calificado de programa académico.',
    etiquetas: ['MinEducación', 'Registro', 'Académico', 'Nuevo'],
    comentarios: 1,
    documentos: 3,
  },
  {
    id: 'oc-007',
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    radicado: 'CGR-2024-00298',
    asunto: 'Auditoría CGR - Ejecución Presupuestal 2024',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-11-05'),
    fechaVencimiento: new Date('2024-12-05'),
    diasRestantes: -13,
    progreso: 100,
    proximaAccion: 'Archivado - Auditoría cerrada sin hallazgos',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 13 días - CGR emitió informe final favorable',
    descripcionCompleta: 'Auditoría de ejecución presupuestal finalizada exitosamente sin hallazgos.',
    etiquetas: ['CGR', 'Auditoría', 'Completado', 'Favorable'],
    comentarios: 8,
    documentos: 22,
  },
];

// ============================================
// CASOS - ASESORÍA JURÍDICA (MOD-03)
// ============================================

const CASOS_ASESORIA_JURIDICA = [
  {
    id: 'aj-001',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-00892',
    asunto: 'Consulta - Viabilidad Jurídica Convenio Interadministrativo',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-15'),
    fechaVencimiento: new Date('2025-01-14'),
    diasRestantes: 27,
    progreso: 30,
    proximaAccion: 'Iniciar análisis jurídico del convenio propuesto',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Asignado a Luis Rodríguez',
    descripcionCompleta: 'Consulta sobre viabilidad jurídica de convenio interadministrativo con entidad pública. Decreto 019/2012: Máximo 30 días hábiles.',
    etiquetas: ['Convenio', 'Análisis', 'Interadministrativo'],
    comentarios: 1,
    documentos: 3,
  },
  {
    id: 'aj-002',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-01023',
    asunto: 'Asesoría - Modificación de Manual de Contratación',
    estado: 'en_proceso' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
      { id: 'u3', nombre: 'Luis Rodríguez', iniciales: 'LR', color: '#4A90E2' },
    ],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2025-01-04'),
    diasRestantes: 17,
    progreso: 55,
    proximaAccion: 'Revisar ajustes propuestos con Dirección Administrativa',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Borrador de modificaciones elaborado',
    descripcionCompleta: 'Asesoría para actualización del Manual de Contratación institucional según nuevas normas. Plazo: 30 días hábiles.',
    etiquetas: ['Contratación', 'Manual', 'Normativo'],
    comentarios: 6,
    documentos: 11,
  },
  {
    id: 'aj-003',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-01145',
    asunto: 'Concepto - Régimen Salarial Docentes Cátedra',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[7],
    fechaCreacion: new Date('2024-12-13'),
    fechaVencimiento: new Date('2024-12-23'),
    diasRestantes: 5,
    progreso: 45,
    proximaAccion: 'Emitir concepto jurídico urgente (plazo crítico)',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 4 horas - Vicerrectoría Académica solicitó priorización',
    descripcionCompleta: 'Concepto jurídico sobre aplicación de régimen salarial para docentes de cátedra. Urgencia: Nómina en proceso.',
    etiquetas: ['Urgente', 'Laboral', 'Docentes', 'Nómina'],
    comentarios: 8,
    documentos: 7,
  },
  {
    id: 'aj-004',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-00978',
    asunto: 'Asesoría - Implementación Ley de Transparencia',
    estado: 'en_revision' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-28'),
    fechaVencimiento: new Date('2024-12-28'),
    diasRestantes: 10,
    progreso: 80,
    proximaAccion: 'Revisar documento final con Jefe OJ',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Documento casi terminado',
    descripcionCompleta: 'Asesoría sobre implementación de obligaciones de la Ley 1712 de 2014 (Transparencia y Acceso a la Información).',
    etiquetas: ['Transparencia', 'Normativo', 'Ley 1712'],
    comentarios: 4,
    documentos: 9,
  },
  {
    id: 'aj-005',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-01067',
    asunto: 'Consulta - Protección de Datos Personales (Habeas Data)',
    estado: 'pendiente_aprobacion' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[2],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2025-01-09'),
    diasRestantes: 22,
    progreso: 90,
    proximaAccion: 'Aprobar concepto para envío a dependencia solicitante',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 6 horas - Concepto elaborado, en espera de firma',
    descripcionCompleta: 'Concepto sobre tratamiento de datos personales en aplicación de la Ley 1581 de 2012.',
    etiquetas: ['Habeas Data', 'Protección de Datos', 'Ley 1581'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'aj-006',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-00845',
    asunto: 'Asesoría - Liquidación de Contratos Vencidos',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-11-15'),
    fechaVencimiento: new Date('2024-12-15'),
    diasRestantes: -3,
    progreso: 100,
    proximaAccion: 'Archivado - Asesoría completada',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Concepto entregado y aplicado',
    descripcionCompleta: 'Asesoría sobre procedimiento de liquidación de contratos vencidos. Completado exitosamente.',
    etiquetas: ['Completado', 'Contratos', 'Liquidación'],
    comentarios: 5,
    documentos: 8,
  },
  {
    id: 'aj-007',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-01189',
    asunto: 'Consulta - Propiedad Intelectual de Investigaciones',
    estado: 'inicial' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-17'),
    fechaVencimiento: new Date('2025-01-16'),
    diasRestantes: 30,
    progreso: 10,
    proximaAccion: 'Solicitar información al Centro de Investigaciones',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Solicitud recibida',
    descripcionCompleta: 'Consulta sobre régimen de propiedad intelectual aplicable a investigaciones institucionales.',
    etiquetas: ['Propiedad Intelectual', 'Investigación', 'Nuevo'],
    comentarios: 0,
    documentos: 2,
  },
  {
    id: 'aj-008',
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    radicado: 'AS-2024-01201',
    asunto: 'Asesoría URGENTE - Conflicto de Interés en Contratación',
    estado: 'vencido' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-25'),
    fechaVencimiento: new Date('2024-12-16'),
    diasRestantes: -2,
    progreso: 60,
    proximaAccion: '¡VENCIDO! Emitir concepto inmediatamente',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 3 días - PLAZO VENCIDO',
    descripcionCompleta: 'Asesoría urgente sobre presunto conflicto de interés en proceso de contratación. VENCIDO - Requiere escalación a MOD-08.',
    etiquetas: ['VENCIDO', 'Urgente', 'Conflicto', 'Contratación'],
    comentarios: 11,
    documentos: 6,
  },
];

// ============================================
// CASOS - JUZGAMIENTO DISCIPLINARIO (MOD-04)
// ============================================

const CASOS_JUZGAMIENTO_DISCIPLINARIO = [
  {
    id: 'jd-001',
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    radicado: 'DISC-2024-00123',
    asunto: 'Proceso Disciplinario - Presunta Irregularidad Administrativa',
    estado: 'en_proceso' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
    ],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-11-20'),
    fechaVencimiento: new Date('2024-12-25'),
    diasRestantes: 7,
    progreso: 55,
    proximaAccion: 'Programar audiencia de descargos',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 5 días - Se practicaron pruebas solicitadas',
    descripcionCompleta: 'Proceso disciplinario interno por presuntas irregularidades en manejo de caja menor.',
    etiquetas: ['Disciplinario', 'Interno', 'Caja Menor'],
    comentarios: 7,
    documentos: 15,
  },
  {
    id: 'jd-002',
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    radicado: 'DISC-2024-00156',
    asunto: 'Proceso Disciplinario - Incumplimiento Horario Laboral',
    estado: 'inicial' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-16'),
    fechaVencimiento: new Date('2025-01-30'),
    diasRestantes: 43,
    progreso: 15,
    proximaAccion: 'Notificar al investigado y correr traslado de cargos',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Queja radicada por Talento Humano',
    descripcionCompleta: 'Proceso disciplinario por incumplimiento reiterado del horario laboral.',
    etiquetas: ['Disciplinario', 'Horario', 'Talento Humano'],
    comentarios: 2,
    documentos: 4,
  },
  {
    id: 'jd-003',
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    radicado: 'DISC-2024-00089',
    asunto: 'Proceso Disciplinario - Uso Indebido de Recursos Institucionales',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-11-10'),
    fechaVencimiento: new Date('2024-12-30'),
    diasRestantes: 12,
    progreso: 75,
    proximaAccion: 'Revisar alegatos de conclusión antes de fallo',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Investigado presentó alegatos',
    descripcionCompleta: 'Proceso disciplinario por presunto uso indebido de vehículo institucional.',
    etiquetas: ['Disciplinario', 'Recursos', 'Vehículo'],
    comentarios: 9,
    documentos: 18,
  },
  {
    id: 'jd-004',
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    radicado: 'DISC-2024-00067',
    asunto: 'Proceso Disciplinario - Conflicto de Interés',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-10-15'),
    fechaVencimiento: new Date('2024-12-10'),
    diasRestantes: -8,
    progreso: 100,
    proximaAccion: 'Archivado - Fallo ejecutoriado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 8 días - Fallo de archivo emitido',
    descripcionCompleta: 'Proceso disciplinario cerrado. No se encontró falta disciplinaria.',
    etiquetas: ['Completado', 'Archivo', 'Sin responsabilidad'],
    comentarios: 6,
    documentos: 12,
  },
  {
    id: 'jd-005',
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    radicado: 'DISC-2024-00178',
    asunto: 'Proceso Disciplinario - Falta Grave: Acoso Laboral',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-01'),
    fechaVencimiento: new Date('2024-12-22'),
    diasRestantes: 4,
    progreso: 65,
    proximaAccion: 'Emitir fallo de primera instancia urgentemente',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 2 horas - Término probatorio vencido',
    descripcionCompleta: 'Proceso disciplinario por falta gravísima: acoso laboral. Requiere fallo urgente.',
    etiquetas: ['Urgente', 'Acoso Laboral', 'Falta Grave'],
    comentarios: 14,
    documentos: 23,
  },
];

// ============================================
// CASOS - PROCESOS COACTIVOS (MOD-05)
// ============================================

const CASOS_PROCESOS_COACTIVOS = [
  {
    id: 'pc-001',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00445',
    asunto: 'Cobro Coactivo - Deuda Matrícula Posgrado',
    estado: 'vencido' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-11-01'),
    fechaVencimiento: new Date('2024-12-15'),
    diasRestantes: -3,
    progreso: 40,
    proximaAccion: '¡VENCIDO! Ejecutar mandamiento de pago',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 4 días - Plazo de respuesta expiró',
    descripcionCompleta: 'Cobro coactivo por deuda de matrícula de programa de especialización. Valor: $8.500.000',
    etiquetas: ['Vencido', 'Urgente', 'Matrícula'],
    comentarios: 9,
    documentos: 6,
  },
  {
    id: 'pc-002',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00567',
    asunto: 'Cobro Coactivo - Certificado Académico',
    estado: 'en_proceso' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-08'),
    fechaVencimiento: new Date('2025-01-08'),
    diasRestantes: 21,
    progreso: 30,
    proximaAccion: 'Notificar mandamiento de pago al deudor',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Título ejecutivo perfeccionado',
    descripcionCompleta: 'Cobro coactivo por certificados académicos no pagados. Valor: $250.000',
    etiquetas: ['Coactivo', 'Certificados', 'En curso'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'pc-003',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00389',
    asunto: 'Cobro Coactivo - Daños a Instalaciones',
    estado: 'requiere_accion' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-12'),
    fechaVencimiento: new Date('2024-12-26'),
    diasRestantes: 8,
    progreso: 50,
    proximaAccion: 'Evaluar excepciones presentadas por el deudor',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 día - Deudor presentó excepciones de mérito',
    descripcionCompleta: 'Cobro coactivo por daños a instalaciones del campus. Valor: $3.200.000',
    etiquetas: ['Coactivo', 'Daños', 'Excepciones'],
    comentarios: 6,
    documentos: 9,
  },
  {
    id: 'pc-004',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00234',
    asunto: 'Cobro Coactivo - Multa Biblioteca',
    estado: 'asignado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-14'),
    fechaVencimiento: new Date('2025-01-28'),
    diasRestantes: 41,
    progreso: 15,
    proximaAccion: 'Iniciar proceso de cobro persuasivo',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 4 días - Caso asignado',
    descripcionCompleta: 'Cobro coactivo por multas de biblioteca no pagadas. Valor: $180.000',
    etiquetas: ['Coactivo', 'Biblioteca', 'Multas'],
    comentarios: 1,
    documentos: 3,
  },
  {
    id: 'pc-005',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00156',
    asunto: 'Cobro Coactivo - Reembolso Beca No Cumplida',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-20'),
    fechaVencimiento: new Date('2024-12-28'),
    diasRestantes: 10,
    progreso: 70,
    proximaAccion: 'Revisar acuerdo de pago propuesto',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Deudor propuso acuerdo de pago',
    descripcionCompleta: 'Cobro coactivo por reembolso de beca estudiantil no cumplida. Valor: $12.000.000',
    etiquetas: ['Coactivo', 'Beca', 'Acuerdo de Pago'],
    comentarios: 7,
    documentos: 11,
  },
  {
    id: 'pc-006',
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    radicado: 'COA-2024-00078',
    asunto: 'Cobro Coactivo - Pérdida de Elementos Laboratorio',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-10-10'),
    fechaVencimiento: new Date('2024-12-05'),
    diasRestantes: -13,
    progreso: 100,
    proximaAccion: 'Archivado - Pago efectuado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 13 días - Deudor pagó la totalidad',
    descripcionCompleta: 'Cobro coactivo completado exitosamente. Valor pagado: $1.850.000',
    etiquetas: ['Completado', 'Pagado', 'Laboratorio'],
    comentarios: 4,
    documentos: 8,
  },
];

// ============================================
// CASOS - BUZÓN DE NOTIFICACIONES (MOD-06)
// ============================================

const CASOS_BUZON_NOTIFICACIONES = [
  {
    id: 'bn-001',
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    radicado: 'NOT-2024-02134',
    asunto: 'Notificación Judicial - Auto Admisorio Demanda Laboral',
    estado: 'inicial' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[1],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-18'),
    fechaVencimiento: new Date('2024-12-19'),
    diasRestantes: 1,
    progreso: 10,
    proximaAccion: 'Revisar y asignar a abogado responsable URGENTE',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 30 min - Notificación recibida por correo certificado',
    descripcionCompleta: 'Notificación de auto admisorio de demanda laboral. Debe escalarse a MOD-01 inmediatamente.',
    etiquetas: ['Nuevo', 'Admisorio', 'Laboral', 'URGENTE'],
    comentarios: 0,
    documentos: 2,
  },
  {
    id: 'bn-002',
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    radicado: 'NOT-2024-02089',
    asunto: 'Notificación - Citación a Audiencia de Juzgamiento',
    estado: 'asignado' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-16'),
    fechaVencimiento: new Date('2024-12-30'),
    diasRestantes: 12,
    progreso: 40,
    proximaAccion: 'Preparar carpeta para audiencia',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Asignado a Luis Rodríguez',
    descripcionCompleta: 'Citación a audiencia de juzgamiento en proceso contencioso administrativo. Fecha audiencia: 15/01/2025.',
    etiquetas: ['Audiencia', 'Contencioso', 'Juzgamiento'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'bn-003',
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    radicado: 'NOT-2024-01956',
    asunto: 'Notificación - Auto de Pruebas',
    estado: 'en_proceso' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2024-12-25'),
    diasRestantes: 7,
    progreso: 60,
    proximaAccion: 'Alistamiento de pruebas solicitadas',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Pruebas en preparación',
    descripcionCompleta: 'Auto de pruebas en proceso ejecutivo. Se deben allegar documentos contables.',
    etiquetas: ['Pruebas', 'Ejecutivo', 'Documentos'],
    comentarios: 4,
    documentos: 7,
  },
  {
    id: 'bn-004',
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    radicado: 'NOT-2024-02201',
    asunto: 'Notificación - Sentencia de Primera Instancia',
    estado: 'requiere_accion' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-17'),
    fechaVencimiento: new Date('2024-12-27'),
    diasRestantes: 9,
    progreso: 20,
    proximaAccion: 'Analizar sentencia y determinar si se apela',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 día - Sentencia recibida',
    descripcionCompleta: 'Sentencia de primera instancia desfavorable. Evaluar viabilidad de recurso de apelación.',
    etiquetas: ['Sentencia', 'Desfavorable', 'Apelación'],
    comentarios: 5,
    documentos: 8,
  },
  {
    id: 'bn-005',
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    radicado: 'NOT-2024-01823',
    asunto: 'Notificación - Auto de Desistimiento',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2024-12-12'),
    diasRestantes: -6,
    progreso: 100,
    proximaAccion: 'Archivado - Proceso terminado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 6 días - Proceso archivado por desistimiento del demandante',
    descripcionCompleta: 'Auto de desistimiento aceptado. Proceso judicial terminado favorablemente.',
    etiquetas: ['Completado', 'Desistimiento', 'Favorable'],
    comentarios: 2,
    documentos: 4,
  },
];

// ============================================
// CASOS - BUZÓN OFICINA JURÍDICA (MOD-07)
// ============================================

const CASOS_BUZON_OJ = [
  {
    id: 'oj-001',
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    radicado: 'OJ-2024-03456',
    asunto: 'Consulta - Interpretación de Reglamento Estudiantil',
    estado: 'inicial' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[1],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-17'),
    fechaVencimiento: new Date('2024-12-22'),
    diasRestantes: 4,
    progreso: 5,
    proximaAccion: 'Evaluar si requiere asesoría formal (escalar a MOD-03)',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Consulta recibida de Bienestar Universitario',
    descripcionCompleta: 'Consulta sobre interpretación de artículo del reglamento estudiantil.',
    etiquetas: ['Consulta', 'Reglamento', 'Estudiantes'],
    comentarios: 1,
    documentos: 2,
  },
  {
    id: 'oj-002',
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    radicado: 'OJ-2024-03512',
    asunto: 'Solicitud - Revisión de Contrato de Arrendamiento',
    estado: 'asignado' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-15'),
    fechaVencimiento: new Date('2024-12-23'),
    diasRestantes: 5,
    progreso: 30,
    proximaAccion: 'Crear asesoría formal en MOD-03',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Asignado para evaluación',
    descripcionCompleta: 'Solicitud de revisión jurídica de contrato de arrendamiento para sede regional.',
    etiquetas: ['Contrato', 'Arrendamiento', 'Regional'],
    comentarios: 2,
    documentos: 4,
  },
  {
    id: 'oj-003',
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    radicado: 'OJ-2024-03467',
    asunto: 'Comunicación - Solicitud de Información de Tercero',
    estado: 'en_proceso' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-12'),
    fechaVencimiento: new Date('2024-12-27'),
    diasRestantes: 9,
    progreso: 55,
    proximaAccion: 'Enviar respuesta a solicitante',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - Información consolidada',
    descripcionCompleta: 'Solicitud de información jurídica de entidad externa aliada.',
    etiquetas: ['Información', 'Tercero', 'Aliado'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'oj-004',
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    radicado: 'OJ-2024-03590',
    asunto: 'Escalamiento - Conflicto Laboral Docente',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[0],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-16'),
    fechaVencimiento: new Date('2024-12-20'),
    diasRestantes: 2,
    progreso: 40,
    proximaAccion: 'Escalar urgentemente a MOD-03 para concepto formal',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 4 horas - Talento Humano solicita priorización',
    descripcionCompleta: 'Conflicto laboral con docente que requiere concepto jurídico urgente.',
    etiquetas: ['URGENTE', 'Laboral', 'Docente', 'Escalamiento'],
    comentarios: 8,
    documentos: 7,
  },
  {
    id: 'oj-005',
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    radicado: 'OJ-2024-03401',
    asunto: 'Consulta - Aplicación de PQRS',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[4],
    fechaCreacion: new Date('2024-12-08'),
    fechaVencimiento: new Date('2024-12-15'),
    diasRestantes: -3,
    progreso: 100,
    proximaAccion: 'Archivado - Respuesta entregada',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Consulta respondida satisfactoriamente',
    descripcionCompleta: 'Consulta sobre aplicación de procedimiento de PQRS. Resuelta exitosamente.',
    etiquetas: ['Completado', 'PQRS', 'Procedimiento'],
    comentarios: 2,
    documentos: 3,
  },
];

// ============================================
// CASOS - PLAN DE ACCIÓN (MOD-08)
// ============================================

const CASOS_PLAN_ACCION = [
  {
    id: 'pa-001',
    moduloId: 'mod-08',
    moduloNombre: 'Plan de Acción',
    radicado: 'PA-2024-00067',
    asunto: 'Plan de Acción - Implementación Nueva Política de Contratación',
    estado: 'en_revision' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[0],
    colaboradores: [
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
      { id: 'u3', nombre: 'Luis Rodríguez', iniciales: 'LR', color: '#4A90E2' },
    ],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-12'),
    fechaVencimiento: new Date('2024-12-30'),
    diasRestantes: 12,
    progreso: 70,
    proximaAccion: 'Revisar avances y aprobar siguiente fase',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Ayer - Coordinador reportó cumplimiento 70%',
    descripcionCompleta: 'Plan de acción para implementar nueva política de contratación institucional derivado de hallazgo de auditoría.',
    etiquetas: ['Plan', 'Contratación', 'Política'],
    comentarios: 4,
    documentos: 10,
  },
  {
    id: 'pa-002',
    moduloId: 'mod-08',
    moduloNombre: 'Plan de Acción',
    radicado: 'PA-2024-00089',
    asunto: 'Plan de Acción - Corrección Vencimientos MOD-03',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[1],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-15'),
    fechaVencimiento: new Date('2024-12-25'),
    diasRestantes: 7,
    progreso: 35,
    proximaAccion: 'Implementar medidas correctivas por asesorías vencidas',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 2 días - Escalado automáticamente por sistema',
    descripcionCompleta: 'Plan de acción correctiva por vencimiento de plazos en módulo de asesorías jurídicas (Decreto 019/2012).',
    etiquetas: ['Correctivo', 'Vencimientos', 'MOD-03', 'URGENTE'],
    comentarios: 9,
    documentos: 6,
  },
  {
    id: 'pa-003',
    moduloId: 'mod-08',
    moduloNombre: 'Plan de Acción',
    radicado: 'PA-2024-00045',
    asunto: 'Plan de Acción - Fortalecimiento Archivo Jurídico',
    estado: 'en_proceso' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-28'),
    fechaVencimiento: new Date('2025-01-15'),
    diasRestantes: 28,
    progreso: 45,
    proximaAccion: 'Continuar digitalización de expedientes físicos',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Digitalizados 150 expedientes',
    descripcionCompleta: 'Plan de acción para fortalecer el archivo jurídico y digitalizar expedientes históricos.',
    etiquetas: ['Archivo', 'Digitalización', 'Mejora'],
    comentarios: 5,
    documentos: 8,
  },
  {
    id: 'pa-004',
    moduloId: 'mod-08',
    moduloNombre: 'Plan de Acción',
    radicado: 'PA-2024-00012',
    asunto: 'Plan de Acción - Capacitación en Nuevo Sistema SIGL',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-01'),
    fechaVencimiento: new Date('2024-12-10'),
    diasRestantes: -8,
    progreso: 100,
    proximaAccion: 'Archivado - Plan completado exitosamente',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 8 días - Capacitación finalizada para todo el equipo',
    descripcionCompleta: 'Plan de capacitación en el nuevo Sistema Integral de Gestión Legal. Completado al 100%.',
    etiquetas: ['Completado', 'Capacitación', 'SIGL'],
    comentarios: 12,
    documentos: 14,
  },
];

// ============================================
// CASOS - RIESGOS (MOD-09)
// ============================================

const CASOS_RIESGOS = [
  {
    id: 'ri-001',
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    radicado: 'RIESGO-2024-00034',
    asunto: 'Riesgo Jurídico - Cambio Normativo en Contratación Estatal',
    estado: 'en_proceso' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2024-12-26'),
    diasRestantes: 8,
    progreso: 45,
    proximaAccion: 'Actualizar matriz de controles y mitigaciones',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Se identificaron nuevos controles',
    descripcionCompleta: 'Evaluación de riesgo jurídico por cambios normativos en Ley de Contratación Estatal.',
    etiquetas: ['Riesgo', 'Normativo', 'Contratación'],
    comentarios: 2,
    documentos: 7,
  },
  {
    id: 'ri-002',
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    radicado: 'RIESGO-2024-00045',
    asunto: 'Riesgo Jurídico - Exposición por Demandas Laborales',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2024-12-24'),
    diasRestantes: 6,
    progreso: 60,
    proximaAccion: 'Presentar informe de riesgo a Comité Directivo',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 1 día - Análisis de exposición completado',
    descripcionCompleta: 'Identificación de riesgo crítico por aumento de demandas laborales. Exposición estimada: $450 millones.',
    etiquetas: ['Riesgo Alto', 'Laboral', 'Exposición', 'CRÍTICO'],
    comentarios: 11,
    documentos: 13,
  },
  {
    id: 'ri-003',
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    radicado: 'RIESGO-2024-00028',
    asunto: 'Riesgo Jurídico - Protección de Datos Personales',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-08'),
    fechaVencimiento: new Date('2025-01-08'),
    diasRestantes: 21,
    progreso: 75,
    proximaAccion: 'Revisar plan de tratamiento de riesgo con Seguridad IT',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Plan de mitigación elaborado',
    descripcionCompleta: 'Evaluación de riesgos de cumplimiento en protección de datos personales (Ley 1581/2012).',
    etiquetas: ['Riesgo', 'Datos Personales', 'Cumplimiento'],
    comentarios: 6,
    documentos: 9,
  },
  {
    id: 'ri-004',
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    radicado: 'RIESGO-2024-00017',
    asunto: 'Riesgo Jurídico - Incumplimiento de Términos Procesales',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-14'),
    fechaVencimiento: new Date('2025-01-14'),
    diasRestantes: 27,
    progreso: 25,
    proximaAccion: 'Evaluar causas raíz de vencimientos recurrentes',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 4 días - Riesgo identificado en auditoría interna',
    descripcionCompleta: 'Identificación de riesgo operacional por incumplimiento recurrente de términos procesales.',
    etiquetas: ['Riesgo', 'Términos', 'Operacional'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'ri-005',
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    radicado: 'RIESGO-2024-00009',
    asunto: 'Riesgo Jurídico - Acreditación Institucional',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-10'),
    fechaVencimiento: new Date('2024-12-10'),
    diasRestantes: -8,
    progreso: 100,
    proximaAccion: 'Archivado - Riesgo mitigado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 8 días - Acreditación renovada exitosamente',
    descripcionCompleta: 'Evaluación de riesgo por vencimiento de acreditación institucional. Riesgo mitigado.',
    etiquetas: ['Completado', 'Acreditación', 'Mitigado'],
    comentarios: 4,
    documentos: 10,
  },
];

// ============================================
// CASOS - PLANES DE MEJORAMIENTO (MOD-10)
// ============================================

const CASOS_PLANES_MEJORAMIENTO = [
  {
    id: 'pm-001',
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    radicado: 'PM-2024-00045',
    asunto: 'Plan de Mejoramiento - Hallazgo CGR en Contratación',
    estado: 'en_proceso' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-25'),
    fechaVencimiento: new Date('2025-01-25'),
    diasRestantes: 38,
    progreso: 40,
    proximaAccion: 'Implementar ajustes en procedimiento de contratación',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 5 días - Primera fase completada',
    descripcionCompleta: 'Plan de mejoramiento derivado de hallazgo de la Contraloría sobre procesos de contratación.',
    etiquetas: ['CGR', 'Hallazgo', 'Contratación'],
    comentarios: 7,
    documentos: 12,
  },
  {
    id: 'pm-002',
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    radicado: 'PM-2024-00067',
    asunto: 'Plan de Mejoramiento - Gestión Documental Jurídica',
    estado: 'requiere_accion' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2024-12-28'),
    diasRestantes: 10,
    progreso: 55,
    proximaAccion: 'Reportar avances al Comité de Gestión Documental',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Se digitalizaron 200 documentos',
    descripcionCompleta: 'Plan de mejoramiento para fortalecer la gestión documental del área jurídica.',
    etiquetas: ['Gestión Documental', 'Mejora', 'Archivo'],
    comentarios: 4,
    documentos: 8,
  },
  {
    id: 'pm-003',
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    radicado: 'PM-2024-00089',
    asunto: 'Plan de Mejoramiento - Tiempos de Respuesta Asesorías',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[1],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
      { id: 'u3', nombre: 'Luis Rodríguez', iniciales: 'LR', color: '#4A90E2' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2025-01-10'),
    diasRestantes: 23,
    progreso: 70,
    proximaAccion: 'Revisar indicadores de cumplimiento de plazos',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Ayer - Indicadores muestran mejora del 25%',
    descripcionCompleta: 'Plan de mejoramiento para reducir tiempos de respuesta en asesorías jurídicas (Decreto 019/2012).',
    etiquetas: ['Asesorías', 'Plazos', 'Decreto 019'],
    comentarios: 9,
    documentos: 11,
  },
  {
    id: 'pm-004',
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    radicado: 'PM-2024-00023',
    asunto: 'Plan de Mejoramiento - Fortalecimiento Defensa Judicial',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-12'),
    fechaVencimiento: new Date('2025-02-12'),
    diasRestantes: 56,
    progreso: 20,
    proximaAccion: 'Elaborar diagnóstico de casos judiciales',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 6 días - Plan asignado a Jorge Torres',
    descripcionCompleta: 'Plan de mejoramiento para fortalecer estrategias de defensa judicial institucional.',
    etiquetas: ['Defensa Judicial', 'Estrategia', 'Fortalecimiento'],
    comentarios: 2,
    documentos: 4,
  },
  {
    id: 'pm-005',
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    radicado: 'PM-2024-00012',
    asunto: 'Plan de Mejoramiento - Auditoría Interna 2024',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-10-01'),
    fechaVencimiento: new Date('2024-12-01'),
    diasRestantes: -17,
    progreso: 100,
    proximaAccion: 'Archivado - Plan cumplido satisfactoriamente',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 17 días - Auditoría de cierre favorable',
    descripcionCompleta: 'Plan de mejoramiento derivado de auditoría interna. Completado exitosamente.',
    etiquetas: ['Completado', 'Auditoría', 'Favorable'],
    comentarios: 8,
    documentos: 15,
  },
];

// ============================================
// CASOS - TÉRMINOS PARA INFORMES (MOD-11)
// ============================================

const CASOS_TERMINOS_INFORMES = [
  {
    id: 'ti-001',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00234',
    asunto: 'Informe Trimestral - Gestión Jurídica Q4 2024',
    estado: 'requiere_accion' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[0],
    colaboradores: [
      { id: 'u2', nombre: 'Ana García', iniciales: 'AG', color: '#0066CC' },
      { id: 'u3', nombre: 'Luis Rodríguez', iniciales: 'LR', color: '#4A90E2' },
    ],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-01'),
    fechaVencimiento: new Date('2024-12-20'),
    diasRestantes: 2,
    progreso: 65,
    proximaAccion: 'Consolidar cifras finales y presentar a Rectoría',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 4 horas - Coordinadores enviaron datos parciales',
    descripcionCompleta: 'Informe trimestral de gestión jurídica para presentación a Rectoría y Consejo Académico.',
    etiquetas: ['Trimestral', 'URGENTE', 'Rectoría'],
    comentarios: 15,
    documentos: 18,
  },
  {
    id: 'ti-002',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00267',
    asunto: 'Informe Mensual - Defensa Judicial Diciembre 2024',
    estado: 'en_proceso' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-10'),
    fechaVencimiento: new Date('2024-12-27'),
    diasRestantes: 9,
    progreso: 50,
    proximaAccion: 'Completar análisis de sentencias del mes',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 1 día - 60% de casos reportados',
    descripcionCompleta: 'Informe mensual de gestión del módulo de Defensa Judicial.',
    etiquetas: ['Mensual', 'Defensa Judicial', 'MOD-01'],
    comentarios: 6,
    documentos: 10,
  },
  {
    id: 'ti-003',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00189',
    asunto: 'Informe Anual - Órganos de Control 2024',
    estado: 'en_revision' as const,
    prioridad: 'alta',
    responsable: USUARIOS_MOCK[3],
    colaboradores: [
      { id: 'u1', nombre: 'Carlos Méndez', iniciales: 'CM', color: '#003DA5' },
    ],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-15'),
    fechaVencimiento: new Date('2025-01-05'),
    diasRestantes: 18,
    progreso: 85,
    proximaAccion: 'Revisión final del Jefe de Oficina Jurídica',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 2 días - Borrador completo enviado a revisión',
    descripcionCompleta: 'Informe anual consolidado de requerimientos de órganos de control.',
    etiquetas: ['Anual', 'Órganos Control', 'MOD-02'],
    comentarios: 12,
    documentos: 22,
  },
  {
    id: 'ti-004',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00301',
    asunto: 'Informe Especial - Exposición Contingente Jurídica',
    estado: 'asignado' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[6],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-14'),
    fechaVencimiento: new Date('2025-01-14'),
    diasRestantes: 27,
    progreso: 30,
    proximaAccion: 'Recopilar valoración de contingencias por proceso',
    puedeActuar: true,
    requiereAtencion: false,
    ultimaActividad: 'Hace 4 días - Asignado para elaboración',
    descripcionCompleta: 'Informe especial de exposición contingente para cierre contable del año fiscal.',
    etiquetas: ['Especial', 'Contingencia', 'Contable'],
    comentarios: 3,
    documentos: 5,
  },
  {
    id: 'ti-005',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00276',
    asunto: 'Informe de Gestión - Asesorías Jurídicas Noviembre 2024',
    estado: 'pendiente_aprobacion' as const,
    prioridad: 'media',
    responsable: USUARIOS_MOCK[2],
    creador: USUARIOS_MOCK[1],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2024-12-18'),
    diasRestantes: 0,
    progreso: 95,
    proximaAccion: 'Aprobar informe para publicación',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 3 horas - Informe completado, en espera de firma',
    descripcionCompleta: 'Informe de gestión del módulo de asesorías jurídicas del mes de noviembre.',
    etiquetas: ['Mensual', 'Asesorías', 'MOD-03'],
    comentarios: 4,
    documentos: 8,
  },
  {
    id: 'ti-006',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00145',
    asunto: 'Informe de Cumplimiento - Planes de Mejoramiento',
    estado: 'completado' as const,
    prioridad: 'baja',
    responsable: USUARIOS_MOCK[7],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-11-20'),
    fechaVencimiento: new Date('2024-12-15'),
    diasRestantes: -3,
    progreso: 100,
    proximaAccion: 'Archivado - Informe entregado',
    puedeActuar: false,
    requiereAtencion: false,
    ultimaActividad: 'Hace 3 días - Informe presentado a Comité de Calidad',
    descripcionCompleta: 'Informe de seguimiento a planes de mejoramiento. Completado y entregado.',
    etiquetas: ['Completado', 'Planes Mejoramiento', 'MOD-10'],
    comentarios: 5,
    documentos: 12,
  },
  {
    id: 'ti-007',
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    radicado: 'INF-2024-00312',
    asunto: 'Informe CGR - Respuesta Auditoría Contratación',
    estado: 'vencido' as const,
    prioridad: 'critica',
    responsable: USUARIOS_MOCK[3],
    creador: USUARIOS_MOCK[0],
    fechaCreacion: new Date('2024-12-05'),
    fechaVencimiento: new Date('2024-12-17'),
    diasRestantes: -1,
    progreso: 80,
    proximaAccion: '¡VENCIDO! Presentar informe inmediatamente',
    puedeActuar: true,
    requiereAtencion: true,
    ultimaActividad: 'Hace 2 días - PLAZO VENCIDO',
    descripcionCompleta: 'Informe de respuesta a auditoría de la CGR sobre contratación. VENCIDO.',
    etiquetas: ['VENCIDO', 'CGR', 'Auditoría', 'URGENTE'],
    comentarios: 18,
    documentos: 14,
  },
];

// ============================================
// CONSOLIDAR TODOS LOS CASOS
// ============================================

export const CASOS_MOCK = [
  ...CASOS_DEFENSA_JUDICIAL,
  ...CASOS_ORGANOS_CONTROL,
  ...CASOS_ASESORIA_JURIDICA,
  ...CASOS_JUZGAMIENTO_DISCIPLINARIO,
  ...CASOS_PROCESOS_COACTIVOS,
  ...CASOS_BUZON_NOTIFICACIONES,
  ...CASOS_BUZON_OJ,
  ...CASOS_PLAN_ACCION,
  ...CASOS_RIESGOS,
  ...CASOS_PLANES_MEJORAMIENTO,
  ...CASOS_TERMINOS_INFORMES,
];

// ============================================
// MÉTRICAS DE MÓDULOS (Actualizadas)
// ============================================

export const METRICAS_MODULOS = [
  {
    moduloId: 'mod-01',
    moduloNombre: 'Defensa Judicial',
    icon: Scale,
    color: '#003DA5',
    total: 145,
    inicial: 8,
    enProceso: 89,
    completado: 42,
    vencidos: 6,
    asignadosAMi: 12,
    porcentajeCompletitud: 29,
  },
  {
    moduloId: 'mod-02',
    moduloNombre: 'Órganos de Control',
    icon: Shield,
    color: '#DC2626',
    total: 67,
    inicial: 4,
    enProceso: 38,
    completado: 23,
    vencidos: 2,
    asignadosAMi: 5,
    porcentajeCompletitud: 34,
  },
  {
    moduloId: 'mod-03',
    moduloNombre: 'Asesoría Jurídica',
    icon: FileQuestion,
    color: '#0066CC',
    total: 234,
    inicial: 15,
    enProceso: 142,
    completado: 72,
    vencidos: 5,
    asignadosAMi: 18,
    porcentajeCompletitud: 31,
  },
  {
    moduloId: 'mod-04',
    moduloNombre: 'Juzgamiento Disciplinario',
    icon: Gavel,
    color: '#7C3AED',
    total: 89,
    inicial: 6,
    enProceso: 56,
    completado: 25,
    vencidos: 2,
    asignadosAMi: 8,
    porcentajeCompletitud: 28,
  },
  {
    moduloId: 'mod-05',
    moduloNombre: 'Procesos Coactivos',
    icon: DollarSign,
    color: '#059669',
    total: 178,
    inicial: 12,
    enProceso: 98,
    completado: 64,
    vencidos: 4,
    asignadosAMi: 14,
    porcentajeCompletitud: 36,
  },
  {
    moduloId: 'mod-06',
    moduloNombre: 'Buzón Notificaciones',
    icon: Mail,
    color: '#EA580C',
    total: 312,
    inicial: 23,
    enProceso: 187,
    completado: 98,
    vencidos: 4,
    asignadosAMi: 6,
    porcentajeCompletitud: 31,
  },
  {
    moduloId: 'mod-07',
    moduloNombre: 'Buzón Oficina Jurídica',
    icon: MessageSquare,
    color: '#0891B2',
    total: 456,
    inicial: 34,
    enProceso: 278,
    completado: 138,
    vencidos: 6,
    asignadosAMi: 9,
    porcentajeCompletitud: 30,
  },
  {
    moduloId: 'mod-08',
    moduloNombre: 'Plan de Acción',
    icon: Target,
    color: '#8B5CF6',
    total: 45,
    inicial: 3,
    enProceso: 28,
    completado: 13,
    vencidos: 1,
    asignadosAMi: 4,
    porcentajeCompletitud: 29,
  },
  {
    moduloId: 'mod-09',
    moduloNombre: 'Riesgos',
    icon: AlertTriangle,
    color: '#DC2626',
    total: 78,
    inicial: 5,
    enProceso: 48,
    completado: 24,
    vencidos: 1,
    asignadosAMi: 7,
    porcentajeCompletitud: 31,
  },
  {
    moduloId: 'mod-10',
    moduloNombre: 'Planes de Mejoramiento',
    icon: TrendingUp,
    color: '#059669',
    total: 92,
    inicial: 7,
    enProceso: 58,
    completado: 26,
    vencidos: 1,
    asignadosAMi: 6,
    porcentajeCompletitud: 28,
  },
  {
    moduloId: 'mod-11',
    moduloNombre: 'Términos para Informes',
    icon: Calendar,
    color: '#0066CC',
    total: 134,
    inicial: 10,
    enProceso: 82,
    completado: 40,
    vencidos: 2,
    asignadosAMi: 11,
    porcentajeCompletitud: 30,
  },
];
