-- ============================================================================
-- Lote 1 · 1.3 — Catálogo de CETAPs (reconciliación)
--
-- Carga los 290 CETAPs del catálogo AUTORITATIVO (02_cetaps.csv), que es el
-- único origen con códigos reales (CET-XXXX). Reparto por tipo:
--   sede_central=1, otro=17, cetap=272
--
-- ⚠️ NO SON 307. El resumen declara 307 CETAPs (15_territoriales_resumen.csv) y
-- el detalle lista 307 nombres (14_territoriales_cetap.csv), pero ese origen NO
-- TRAE CÓDIGOS. Reconciliación por nombre normalizado contra el catálogo:
--     253  emparejan exacto
--       5  emparejan quitando el artículo inicial (El/La): p. ej.
--          'Carmen de Viboral' -> CET-0013 'El Carmen de Viboral'
--       3  emparejan con distancia 1-2 y son claramente el mismo sitio:
--          Mompox/Mompós, Tierra Alta/Tierralta, Itsmina/Istmina
--      46  NO tienen contraparte en el catálogo (Amalfi, Segovia, Guapi,
--          Tumaco, Buga, Zapatoca, Ambalema, los Resguardos del Huila...)
--
-- ⚠️ NO se aplicó emparejamiento difuso automático. El pase con distancia<=3
-- produjo falsos positivos demostrables —'Pácora'->'Patía', 'Samaná'->'Istmina',
-- 'Cajicá'->'Patía'— que habrían corrompido el catálogo en silencio. Entre
-- perder filas y corromperlas, se reporta el hueco.
--
-- No hay campo estructurado que una los dos orígenes: el detalle solo tiene
-- nombre. Por la misma regla del histórico, el nombre es sugerencia, no verdad.
--
-- Los 46 faltantes requieren decisión de quien tenga el catálogo oficial: o se
-- les asigna código, o se acepta que 307 es un conteo declarativo y el catálogo
-- real tiene 290.
--
-- Forward-only e idempotente. SQL puro.
--
-- ⚠️ APROVISIONAMIENTO DE DATOS DE DESARROLLO, no el mecanismo de producción.
-- Escribe fuera del esquema del módulo (academic_work_plan / auth) siguiendo el
-- precedente de las migraciones 007 y 011. No toca código del PTA.
-- RN-09 sigue vigente: el RUND es de solo lectura para las decanaturas.
-- ============================================================================

INSERT INTO academic_work_plan.cetap
       (codigo, nombre, nombre_normalizado, id_direccion_territorial, tipo, latitud, longitud, activo)
SELECT v.codigo, v.nombre, v.nombre_norm, dt.id, v.tipo, v.lat, v.lon, v.activo
  FROM (VALUES
    ('CET-0288', 'Sede Central', 'sedecentral', 'SC', 'sede_central', 4.6486, -74.0828, true),
    ('CET-0001', 'OTRO', 'otro', 'SC', 'otro', NULL, NULL, true),
    ('CET-0003', 'Amagá', 'amaga', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0004', 'Andes', 'andes', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0005', 'Apartadó', 'apartado', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0006', 'Arboletes', 'arboletes', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0007', 'Caicedo', 'caicedo', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0008', 'Caucasia', 'caucasia', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0009', 'Chigorodó', 'chigorodo', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0010', 'Ciudad Bolívar', 'ciudadbolivar', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0011', 'Dabeiba', 'dabeiba', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0012', 'Ebéjico', 'ebejico', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0013', 'El Carmen de Viboral', 'elcarmendeviboral', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0014', 'El Santuario', 'elsantuario', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0015', 'Fredonia', 'fredonia', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0016', 'Giraldo', 'giraldo', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0017', 'Ituango', 'ituango', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0018', 'Jardín', 'jardin', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0289', 'Jericó', 'jerico', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0019', 'La Pintada', 'lapintada', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0002', 'Medellín', 'medellin', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0020', 'Mutatá', 'mutata', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0021', 'Necoclí', 'necocli', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0022', 'Puerto Berrío', 'puertoberrio', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0290', 'Sabanalarga', 'sabanalarga', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0023', 'San Carlos', 'sancarlos', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0024', 'San Jerónimo', 'sanjeronimo', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0025', 'San Pedro de Urabá', 'sanpedrodeuraba', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0026', 'Santafe De Antioquia', 'santafedeantioquia', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0027', 'Sonsón', 'sonson', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0028', 'Titiribí', 'titiribi', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0029', 'Turbo', 'turbo', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0030', 'Valdivia', 'valdivia', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0031', 'Vegachí', 'vegachi', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0032', 'Yarumal', 'yarumal', 'DT-001', 'cetap', NULL, NULL, true),
    ('CET-0033', 'OTRO', 'otro', 'DT-001', 'otro', NULL, NULL, true),
    ('CET-0034', 'Barranquilla', 'barranquilla', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0035', 'Bosconia', 'bosconia', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0036', 'La Jagua de Ibirico', 'lajaguadeibirico', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0037', 'Malambo', 'malambo', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0038', 'Santa Marta', 'santamarta', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0039', 'Suan de la Trinidad', 'suandelatrinidad', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0040', 'Uribia', 'uribia', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0041', 'Valledupar', 'valledupar', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0042', 'Villanueva', 'villanueva', 'DT-002', 'cetap', NULL, NULL, true),
    ('CET-0043', 'OTRO', 'otro', 'DT-002', 'otro', NULL, NULL, true),
    ('CET-0045', 'Canalete', 'canalete', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0044', 'Cartagena', 'cartagena', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0046', 'Corozal', 'corozal', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0047', 'La Unión Sucre', 'launionsucre', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0048', 'Lorica', 'lorica', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0049', 'Los Córdobas', 'loscordobas', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0050', 'Magangué', 'magangue', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0051', 'Majagual', 'majagual', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0052', 'Mompós', 'mompos', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0053', 'Montelíbano', 'montelibano', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0054', 'Montería', 'monteria', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0055', 'Providencia', 'providencia', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0057', 'San Andres de Sotavento Resguardo Indigena', 'sanandresdesotaventoresguardoindigena', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0056', 'San Andrés', 'sanandres', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0058', 'San Antero', 'sanantero', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0059', 'San Luis de Sincé', 'sanluisdesince', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0060', 'Sincelejo', 'sincelejo', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0061', 'Tierralta', 'tierralta', 'DT-003', 'cetap', NULL, NULL, true),
    ('CET-0062', 'OTRO', 'otro', 'DT-003', 'otro', NULL, NULL, true),
    ('CET-0064', 'Chiquinquirá', 'chiquinquira', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0065', 'Duitama', 'duitama', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0066', 'Garagoa', 'garagoa', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0067', 'Guateque', 'guateque', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0068', 'Miraflores', 'miraflores', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0069', 'Moniquirá', 'moniquira', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0070', 'Monterrey', 'monterrey', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0071', 'Otanche', 'otanche', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0072', 'Paz de Ariporo', 'pazdeariporo', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0073', 'Puerto Boyacá', 'puertoboyaca', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0074', 'Soatá', 'soata', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0075', 'Sogamoso', 'sogamoso', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0063', 'Tunja', 'tunja', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0076', 'Yopal', 'yopal', 'DT-004', 'cetap', NULL, NULL, true),
    ('CET-0077', 'OTRO', 'otro', 'DT-004', 'otro', NULL, NULL, true),
    ('CET-0079', 'Aguadas', 'aguadas', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0080', 'Anserma', 'anserma', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0081', 'Belalcázar', 'belalcazar', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0082', 'Chinchiná', 'chinchina', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0083', 'Filadelfia', 'filadelfia', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0084', 'La Dorada', 'ladorada', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0078', 'Manizales', 'manizales', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0085', 'Manzanares', 'manzanares', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0086', 'Marmato', 'marmato', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0087', 'Neira', 'neira', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0088', 'Riosucio', 'riosucio', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0089', 'Salamina', 'salamina', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0090', 'Supía', 'supia', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0091', 'Viterbo', 'viterbo', 'DT-005', 'cetap', NULL, NULL, true),
    ('CET-0092', 'OTRO', 'otro', 'DT-005', 'otro', NULL, NULL, true),
    ('CET-0100', 'Caldono', 'caldono', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0101', 'Miranda', 'miranda', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0102', 'Patía', 'patia', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0099', 'Popayan', 'popayan', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0103', 'Rosas', 'rosas', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0104', 'Santander De Quilichao', 'santanderdequilichao', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0105', 'SilviaGuambia', 'silviaguambia', 'DT-006', 'cetap', NULL, NULL, true),
    ('CET-0106', 'OTRO', 'otro', 'DT-006', 'otro', NULL, NULL, true),
    ('CET-0094', 'Acandi', 'acandi', 'DT-007', 'cetap', NULL, NULL, true),
    ('CET-0095', 'Istmina', 'istmina', 'DT-007', 'cetap', NULL, NULL, true),
    ('CET-0093', 'Quibdo', 'quibdo', 'DT-007', 'cetap', NULL, NULL, true),
    ('CET-0096', 'Riosucio', 'riosucio', 'DT-007', 'cetap', NULL, NULL, true),
    ('CET-0097', 'Unguia', 'unguia', 'DT-007', 'cetap', NULL, NULL, true),
    ('CET-0098', 'OTRO', 'otro', 'DT-007', 'otro', NULL, NULL, true),
    ('CET-0108', 'Agua de Dios', 'aguadedios', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0111', 'Chipaque', 'chipaque', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0110', 'Chía', 'chia', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0112', 'Cota', 'cota', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0109', 'Cáqueza', 'caqueza', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0113', 'El Colegio', 'elcolegio', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0114', 'Facatativá', 'facatativa', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0115', 'Funza', 'funza', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0107', 'Fusagasugá', 'fusagasuga', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0116', 'Gachalá', 'gachala', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0117', 'Gachetá', 'gacheta', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0118', 'Girardot', 'girardot', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0119', 'Guachetá', 'guacheta', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0120', 'Guaduas', 'guaduas', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0121', 'La Mesa', 'lamesa', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0122', 'Madrid', 'madrid', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0123', 'Mosquera', 'mosquera', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0124', 'Pacho', 'pacho', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0125', 'Puerto Salgar', 'puertosalgar', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0126', 'Ricaurte', 'ricaurte', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0127', 'San Juan de Rioseco', 'sanjuanderioseco', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0128', 'Soacha', 'soacha', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0129', 'Tena', 'tena', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0130', 'Tibiritá', 'tibirita', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0131', 'Tocancipá', 'tocancipa', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0132', 'Villeta', 'villeta', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0133', 'Zipaquirá', 'zipaquira', 'DT-008', 'cetap', NULL, NULL, true),
    ('CET-0134', 'OTRO', 'otro', 'DT-008', 'otro', NULL, NULL, true),
    ('CET-0136', 'Acevedo', 'acevedo', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0137', 'Algeciras', 'algeciras', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0138', 'Belén de Los Andaquíes', 'belendelosandaquies', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0139', 'Cartagena del Chairá', 'cartagenadelchaira', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0140', 'Colombia Huila', 'colombiahuila', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0141', 'El Paujíl', 'elpaujil', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0142', 'Florencia', 'florencia', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0143', 'Garzón', 'garzon', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0144', 'Isnos', 'isnos', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0145', 'La Montañita', 'lamontanita', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0146', 'La Plata', 'laplata', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0147', 'Mocoa', 'mocoa', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0135', 'Neiva', 'neiva', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0148', 'Orito', 'orito', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0150', 'Pitalito', 'pitalito', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0151', 'Puerto Asís', 'puertoasis', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0152', 'Puerto Leguízamo', 'puertoleguizamo', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0153', 'Puerto Rico', 'puertorico', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0149', 'Páez', 'paez', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0154', 'San Agustín', 'sanagustin', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0155', 'San Vicente del Caguán', 'sanvicentedelcaguan', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0156', 'Santa María', 'santamaria', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0157', 'Solano', 'solano', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0158', 'Suaza', 'suaza', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0159', 'Valparaíso', 'valparaiso', 'DT-009', 'cetap', NULL, NULL, true),
    ('CET-0160', 'OTRO', 'otro', 'DT-009', 'otro', NULL, NULL, true),
    ('CET-0162', 'Acacías', 'acacias', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0163', 'Barranca de Upía', 'barrancadeupia', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0164', 'Cabuyaro', 'cabuyaro', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0165', 'Cumaral', 'cumaral', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0166', 'Cumaribo', 'cumaribo', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0167', 'El Castillo', 'elcastillo', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0168', 'Fuente de Oro', 'fuentedeoro', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0169', 'Granada', 'granada', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0170', 'Inírida', 'inirida', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0171', 'La Macarena', 'lamacarena', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0172', 'La Primavera', 'laprimavera', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0173', 'La Uribe', 'lauribe', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0174', 'Lejanías', 'lejanias', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0175', 'Leticia', 'leticia', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0176', 'Mesetas', 'mesetas', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0177', 'Mitú', 'mitu', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0178', 'Puerto Carreño', 'puertocarreno', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0179', 'Puerto Concordia', 'puertoconcordia', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0180', 'Puerto Gaitán', 'puertogaitan', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0181', 'Puerto Lleras', 'puertolleras', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0182', 'Puerto López', 'puertolopez', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0183', 'Puerto Nariño', 'puertonarino', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0184', 'Puerto Rico', 'puertorico', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0185', 'San José del Guaviare', 'sanjosedelguaviare', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0186', 'San Martín', 'sanmartin', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0187', 'Santa Rosalía', 'santarosalia', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0161', 'Villavicencio', 'villavicencio', 'DT-010', 'cetap', NULL, NULL, true),
    ('CET-0188', 'OTRO', 'otro', 'DT-010', 'otro', NULL, NULL, true),
    ('CET-0190', 'Albán', 'alban', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0191', 'Barbacoas', 'barbacoas', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0192', 'Buesaco', 'buesaco', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0193', 'Chachagüí', 'chachagui', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0194', 'Consacá', 'consaca', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0195', 'Cumbal', 'cumbal', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0196', 'El Peñol', 'elpenol', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0197', 'El Tablón de Gómez', 'eltablondegomez', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0198', 'El Tambo', 'eltambo', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0199', 'Funes', 'funes', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0200', 'Guaitarilla', 'guaitarilla', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0201', 'Gualmatán', 'gualmatan', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0202', 'Imués', 'imues', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0203', 'Ipiales', 'ipiales', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0204', 'La Unión Nariño', 'launionnarino', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0205', 'Linares', 'linares', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0206', 'Ospina', 'ospina', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0189', 'Pasto', 'pasto', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0207', 'Policarpa', 'policarpa', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0208', 'Puerres', 'puerres', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0209', 'Ricaurte', 'ricaurte', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0210', 'Samaniego', 'samaniego', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0211', 'San Andrés de Tumaco', 'sanandresdetumaco', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0212', 'San Lorenzo Nariño', 'sanlorenzonarino', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0213', 'San Pablo', 'sanpablo', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0214', 'Sandoná', 'sandona', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0215', 'Santacruz Guachavez', 'santacruzguachavez', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0216', 'Sibundoy', 'sibundoy', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0217', 'Túquerres', 'tuquerres', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0218', 'Yacuanquer', 'yacuanquer', 'DT-011', 'cetap', NULL, NULL, true),
    ('CET-0219', 'OTRO', 'otro', 'DT-011', 'otro', NULL, NULL, true),
    ('CET-0234', 'Arauca', 'arauca', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0235', 'Arauquita', 'arauquita', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0222', 'Arboledas', 'arboledas', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0223', 'Chinácota', 'chinacota', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0224', 'Convención', 'convencion', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0236', 'Cravo Norte', 'cravonorte', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0220', 'Cúcuta', 'cucuta', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0225', 'El Tarra', 'eltarra', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0237', 'Fortul', 'fortul', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0226', 'Gramalote', 'gramalote', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0227', 'Hacarí', 'hacari', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0228', 'Ocaña', 'ocana', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0229', 'Pamplona', 'pamplona', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0238', 'Puerto Rondón', 'puertorondon', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0230', 'Ragonvalia', 'ragonvalia', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0231', 'Salazar', 'salazar', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0239', 'Saravena', 'saravena', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0232', 'Sardinata', 'sardinata', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0240', 'Tame', 'tame', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0233', 'Tibú', 'tibu', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0221', 'Ábrego', 'abrego', 'DT-012', 'cetap', NULL, NULL, true),
    ('CET-0241', 'OTRO', 'otro', 'DT-012', 'otro', NULL, NULL, true),
    ('CET-0243', 'Armenia', 'armenia', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0244', 'Belén de Umbría', 'belendeumbria', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0245', 'Circasia', 'circasia', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0246', 'Dosquebradas', 'dosquebradas', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0247', 'Filandia', 'filandia', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0248', 'Génova', 'genova', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0249', 'Marsella', 'marsella', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0242', 'Pereira', 'pereira', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0250', 'Pueblo Rico', 'pueblorico', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0251', 'Quinchía', 'quinchia', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0252', 'Santa Rosa de Cabal', 'santarosadecabal', 'DT-013', 'cetap', NULL, NULL, true),
    ('CET-0253', 'OTRO', 'otro', 'DT-013', 'otro', NULL, NULL, true),
    ('CET-0255', 'Barrancabermeja', 'barrancabermeja', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0254', 'Bucaramanga', 'bucaramanga', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0256', 'Cimitarra', 'cimitarra', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0257', 'Málaga', 'malaga', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0258', 'Oiba', 'oiba', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0259', 'Puente Nacional', 'puentenacional', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0260', 'San Gil', 'sangil', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0261', 'Santa Rosa del Sur', 'santarosadelsur', 'DT-014', 'cetap', NULL, NULL, true),
    ('CET-0262', 'OTRO', 'otro', 'DT-014', 'otro', NULL, NULL, true),
    ('CET-0264', 'Ataco', 'ataco', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0265', 'Chaparral', 'chaparral', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0266', 'Coyaima', 'coyaima', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0267', 'Espinal', 'espinal', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0268', 'Flandes', 'flandes', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0269', 'Fresno', 'fresno', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0263', 'Ibagué', 'ibague', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0270', 'Líbano', 'libano', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0271', 'Mariquita', 'mariquita', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0272', 'Melgar', 'melgar', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0273', 'Natagaima', 'natagaima', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0274', 'Planadas', 'planadas', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0275', 'Purificación', 'purificacion', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0276', 'Valle de San Juan', 'valledesanjuan', 'DT-015', 'cetap', NULL, NULL, true),
    ('CET-0277', 'OTRO', 'otro', 'DT-015', 'otro', NULL, NULL, true),
    ('CET-0279', 'Buenaventura', 'buenaventura', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0278', 'Cali', 'cali', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0280', 'Cartago', 'cartago', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0281', 'Florida', 'florida', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0282', 'Guadalajara de Buga', 'guadalajaradebuga', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0283', 'La Unión Valle', 'launionvalle', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0284', 'Pradera', 'pradera', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0285', 'Sevilla', 'sevilla', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0286', 'Tuluá', 'tulua', 'DT-016', 'cetap', NULL, NULL, true),
    ('CET-0287', 'OTRO', 'otro', 'DT-016', 'otro', NULL, NULL, true)
  ) AS v(codigo, nombre, nombre_norm, codigo_dt, tipo, lat, lon, activo)
  JOIN academic_work_plan.direccion_territorial dt ON dt.codigo = v.codigo_dt
 WHERE NOT EXISTS (SELECT 1 FROM academic_work_plan.cetap c WHERE c.codigo = v.codigo);

-- Canario: el conteo cargado y que ninguno quedó sin territorial.
DO $$
DECLARE
  v_total INT; v_huerfanos INT;
BEGIN
  SELECT COUNT(*) INTO v_total FROM academic_work_plan.cetap;
  SELECT COUNT(*) INTO v_huerfanos
    FROM academic_work_plan.cetap c
    LEFT JOIN academic_work_plan.direccion_territorial dt ON dt.id = c.id_direccion_territorial
   WHERE dt.id IS NULL;

  RAISE NOTICE '020: cetaps=% huerfanos=%', v_total, v_huerfanos;

  IF v_total <> 290 THEN
    RAISE EXCEPTION '020: se esperaban 290 cetaps del catalogo y hay %', v_total;
  END IF;
  IF v_huerfanos > 0 THEN
    RAISE EXCEPTION '020: % cetaps sin direccion territorial', v_huerfanos;
  END IF;
END $$;
