export const GRADUATE_PROGRAM_OPTIONS = [
  'ADMINISTRACIÓN PÚBLICA',
  'ADMINISTRACIÓN PÚBLICA TERRITORIAL',
  'ESPECIALIZACIÓN EN ALTA DIRECCIÓN DEL ESTADO',
  'ESPECIALIZACIÓN EN DERECHOS HUMANOS',
  'ESPECIALIZACIÓN EN FINANZAS PÚBLICAS',
  'ESPECIALIZACIÓN EN GERENCIA SOCIAL',
  'ESPECIALIZACIÓN EN GESTIÓN PÚBLICA',
  'ESPECIALIZACIÓN EN GESTIÓN Y PLANIFICACIÓN DEL DESARROLLO URBANO Y REGIONAL',
  'ESPECIALIZACIÓN EN PROYECTOS DE DESARROLLO',
  'MAESTRÍA EN ADMINISTRACIÓN PÚBLICA',
  'MAESTRÍA EN DERECHOS HUMANOS, GESTIÓN DE LA TRANSICIÓN Y POSCONFLICTO',
] as const;
