-- ============================================================================
-- 013 · Catálogo de actividades y su aplicabilidad por modalidad
--
-- Generado por scripts/generar-seed-matriz.mjs desde A2_MATRIZ_FLUJO.md.
-- NO EDITAR A MANO: corregir la matriz y volver a ejecutar el script.
--
-- La matriz es la fuente única de verdad funcional, y aún no está validada
-- por la Dirección de Contratación. Por eso el seed es idempotente: cuando
-- corrijan una celda basta regenerar y volver a aplicar, sin migración nueva.
--
-- Actividades: 63
-- Aplicabilidad: 693 filas
-- ============================================================================

-- Las tablas ya existen desde 010_cdp.sql: aqui solo se siembran los datos.
-- ------------------------------------------------------------ actividades --

INSERT INTO hiring.actividades (numeral, etapa, nombre, descripcion, orden) VALUES
  ('1.1', 1, 'Identificación de necesidad', 'Áreas misionales y de soporte identifican bienes, servicios u obras para la vigencia.', 1),
  ('1.2', 1, 'Elaborar justificación de necesidad', 'Elaboración de Estudio Previo y/o anexo técnico , cantidad y cronograma.', 2),
  ('1.3', 1, 'Consolidar matriz de necesidades', 'Consolidación en la herramienta ESAP. Herramienta de control presupuestal con mayor detalle que el PAA.', 3),
  ('1.4', 1, 'Validar matriz de necesidades', 'Priorización, depuración de duplicidades y aprobación del alcance total.', 4),
  ('2.1', 2, 'Consolidar Plan Anual de Adquisiciones', 'Diligenciamiento de plantilla SECOP 2', 1),
  ('2.2', 2, 'aprobación del PAA', 'aprueba comité de contratación', 2),
  ('2.3', 2, 'Publicar en SECOP II', 'publicación antes del 31 enero.', 3),
  ('2.4', 2, 'Actualizar cuando sea necesario', '¿La necesidad está incluida en el PAA? ├ No → Actualizar PAA → Regresar └ Sí', 4),
  ('3.1', 3, 'Elaboración de Estudios Previos y demás documentos previos', 'Descripción de necesidad, fundamento jurídico, modalidad propuesta. Obligatorio Ley 80/1993.', 1),
  ('3.2', 3, 'Elaboración análisis del sector y estudio de mercado', 'Consulta de proveedores, precios de mercado y fichas técnicas para estimar el valor.', 2),
  ('3.3', 3, 'Radicación a la Dirección de contratación', 'debe genrar un consecutivo a traves del aplicativo de gestion documental de la escuela active document, revisar proceso otic', 3),
  ('3.4', 3, 'Revisión y reparto en la Dirección de contratación', 'revisiones, mesas de trabajo y observaciones al estudio previos', 4),
  ('3.5', 3, 'Definir modalidad de contratación', 'Licitación, Selección Abreviada, Concurso de Méritos, Directa o Mínima Cuantía según Decreto 1082/2015.', 5),
  ('3.6', 3, 'Causal de contratación', 'filtro según la modalidad', 6),
  ('3.7', 3, 'Comité de contratación', 'Va o No / observa o no / aprueba o no', 7),
  ('4.1', 4, 'Solicitud de CDP', 'El área solicitante radica solicitud formal. Requiere enlace con KLIC.', 1),
  ('4.2', 4, 'Verificar disponibilidad presupuestal', 'Financiera verifica disponibilidad presupuestal.', 2),
  ('4.3', 4, 'expedición de CDP', 'Sin CDP no se puede continuar. El CDP certifica recursos disponibles y queda afectado al proceso.', 3),
  ('4.4', 4, 'Adjuntar al expediente', 'se debe cargar el cdp para consulta en las siguientes etapas', 4),
  ('5.1', 5, 'Elaboración de documentos a cargo de la dirección de contratación', 'aviso de convocatoria, proyecto de pliegos y anexos, borrador de minuta del contrato, invitación pública', 1),
  ('5.2', 5, 'Elaboración de cronograma', 'genera alertas para futuros filtros y sirve de insumo para SECOP o TVEC', 2),
  ('5.3', 5, 'Publicación en SECOP II', 'Se crea el proceso, se suben todos los documentos', 3),
  ('5.4', 5, 'Publicación en pagina web ESAP', 'se realiza en la pagina web de la esap pero se adjunta el soporte de la publicacion en el expedient', 4),
  ('5.5', 5, 'Limitación a MiPymes', 'Se crea un filtro', 5),
  ('5.6', 5, 'Recepción de observaciones', 'Atención de preguntas en el término establecido', 6),
  ('5.7', 5, 'Apertura del proceso', 'Documento de respuesta a obs, proyecto de pliego, resolución de apertura, pliego definitivo y anexos definitivos', 7),
  ('5.8', 5, 'CDP', 'Obligatorio / no obligatorio', 8),
  ('5.9', 5, 'Manifestación de interés', 'campo para nota de trazabilidad, alerta según cronograma de fecha Max para manifestar interés', 9),
  ('5.10', 5, 'sorteo', 'campo de si/no, adjunta soporte', 10),
  ('5.11', 5, 'publicación de Manifestación de interés', 'adjuntar soporte', 11),
  ('5.12', 5, 'Audiencia riesgos y aclaración de pliegos', 'Salida: acta y documento de respuesta a observaciones', 12),
  ('5.13', 5, 'Adendas', 'Documento vinculante (A partir de la apertura pueden generarse en cualquier momento)', 13),
  ('6.1', 6, 'Cierre', 'Ofertas recibidas por SECOP II - Salida: Memorando designación comité asesor evaluador (Dirigido del ordenador del gasto a los integrantes)', 1),
  ('6.2', 6, 'Evaluación de ofertas', 'El comité verifica requisitos jurídicos, financieros y técnicos.', 2),
  ('6.3', 6, 'Informe de evaluación preliminar', 'Informe de evaluación publicado en SECOP 2.', 3),
  ('6.4', 6, 'Publicación y Traslado del informe de evaluación preliminar', 'Si no hay ofertas habilitadas → proceso desierto.', 4),
  ('6.5', 6, 'Recepción de subsanaciones y observaciones al informe de ev. Preliminar', 'campo de cargar información', 5),
  ('6.6', 6, 'Respuestas a las observaciones', 'Documento Financiero, técnico y jurídico', 6),
  ('6.7', 6, 'Informe previo a audiencia de adjudicación', 'Informe de evaluación publicado en SECOP 2.', 7),
  ('6.8', 6, 'informe previo al evento de subasta', 'generado en la direccion de contratacion por los profesionales a cargo del proceso', 8),
  ('6.9', 6, 'Apertura de sobre económico en previo a subasta', 'se adelanta la apertura de las ofertas economicas de los oferentes habilitados en secop 2', 9),
  ('6.10', 6, 'evento de subasta', 'se adelanta a traves de la plataforma de subasta secop2', 10),
  ('7.1', 7, 'Audiencia de adjudicación', 'Cargue de observaciones y respuestas, acta y grabaciones.', 1),
  ('7.2', 7, 'Apertura de sobre económico en audiencia de adjudicación', 'Aplica solo para la licitación de obra pública', 2),
  ('7.3', 7, 'Informe de evaluación definitivo', 'informe de evaluacion que se genera luego de la audiencia de adjudicacion', 3),
  ('7.4', 7, 'Acto de adjudicación', 'Ordenador del gasto emite resolución o acto administrativo. Se notifica y publica en SECOP 2.', 4),
  ('8.1', 8, 'Elaboración de contrato', 'Firma por representante legal de la entidad y el contratista. Perfeccionamiento del contrato.', 1),
  ('8.2', 8, 'Designación de supervisor', 'Salida: Designación formal del supervisor por parte del ordenador del gasto. Y que se le alerte al supervisor', 2),
  ('8.3', 8, 'Expedición de RP', 'Compromiso firme de recursos. El RP sustituye al CDP en la etapa contractual.', 3),
  ('8.4', 8, 'Constitución de garantías', 'Desglosar los amparos para el control de las fechas de vencimiento. Aprobación/rechazo en SECOP II o mediante documento de aprobación (ya existe la plantilla)', 4),
  ('8.5', 8, 'ARL', 'Cuando la entidad realiza la afiliación o cuando la realiza directamente el contratista. Crear campo obligatorio para personas naturales.', 5),
  ('8.6', 8, 'Comunicación de inicio', 'Comunicación de que ya encuentran cumplidos los requisitos anteriores.', 6),
  ('8.7', 8, 'Acta de inicio (cuando aplique)', 'Salida: plantilla que ya existe', 7),
  ('8.8', 8, 'Publicación en pagina web ESAP', '150', 8),
  ('9.1', 9, 'Reunión de inicio', 'Socialización de alcance, cronograma y entregables. Acta de inicio firmada por ambas partes, si fue pactada en el contrato.', 1),
  ('9.2', 9, 'Ejecución y supervisión del contrato', 'Ejecución y supervisión', 2),
  ('9.3', 9, 'Reasignación de supervisión', 'Puede darse en cualquier momento durante la ejecución y surte una designación del mismo ordenador del gasto.', 3),
  ('9.4', 9, 'Trámite de pagos', 'Requiere enlace con KLIC', 4),
  ('9.5', 9, 'Modificaciones contractuales', 'Según tipos de modificaciones explicadas en mesa de trabajo del 9 de junio de 2026. Surte mismo trámite del proceso en versión mas corta.', 5),
  ('10.1', 10, 'Informe final de ejecución', 'Informe final según aplique.', 1),
  ('10.2', 10, 'Liquidación', 'Acta de liquidación si el contrato lo requiere. RECORDAR FILTRO según tipología contractual que fue revisada en sesión del 9 de junio', 2),
  ('10.3', 10, 'Cierre', 'Cierre según tipología contractual.', 3),
  ('10.4', 10, 'Archivar expediente contractual', 'Archivo expediente completo.', 4)
ON CONFLICT (numeral) DO UPDATE
  SET etapa = EXCLUDED.etapa,
      nombre = EXCLUDED.nombre,
      descripcion = EXCLUDED.descripcion,
      orden = EXCLUDED.orden;

-- -------------------------------------------------------- aplicabilidad ---
-- Solo se registran los NO: la ausencia de fila significa que la actividad
-- aplica, que es el caso mayoritario. De 693 celdas, la inmensa mayoria son SI.

DELETE FROM hiring.actividades_excluidas WHERE numeral IN (
  '1.1', '1.2', '1.3', '1.4', '2.1', '2.2', '2.3', '2.4', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '4.1', '4.2', '4.3', '4.4', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '5.10', '5.11', '5.12', '5.13', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7', '6.8', '6.9', '6.10', '7.1', '7.2', '7.3', '7.4', '8.1', '8.2', '8.3', '8.4', '8.5', '8.6', '8.7', '8.8', '9.1', '9.2', '9.3', '9.4', '9.5', '10.1', '10.2', '10.3', '10.4'
);

INSERT INTO hiring.actividades_excluidas (numeral, modalidad, motivo) VALUES
  ('1.1', 'ENAJENACION_SUBASTA', NULL),
  ('1.3', 'ENAJENACION_SUBASTA', NULL),
  ('1.4', 'ENAJENACION_SUBASTA', NULL),
  ('2.1', 'ENAJENACION_SUBASTA', NULL),
  ('2.2', 'ENAJENACION_SUBASTA', NULL),
  ('2.3', 'ENAJENACION_SUBASTA', NULL),
  ('2.4', 'ENAJENACION_SUBASTA', NULL),
  ('3.5', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('3.6', 'LICITACION_PUBLICA', NULL),
  ('3.6', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('3.6', 'ENAJENACION_SUBASTA', NULL),
  ('3.6', 'ABREVIADA_TVEC', NULL),
  ('3.6', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('3.6', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('3.6', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('3.6', 'MINIMA_CUANTIA', NULL),
  ('3.6', 'REGIMEN_ESPECIAL_092', NULL),
  ('3.7', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('3.7', 'ENAJENACION_SUBASTA', NULL),
  ('3.7', 'MINIMA_CUANTIA', NULL),
  ('4.1', 'ENAJENACION_SUBASTA', NULL),
  ('4.2', 'ENAJENACION_SUBASTA', NULL),
  ('4.3', 'ENAJENACION_SUBASTA', NULL),
  ('4.4', 'ENAJENACION_SUBASTA', NULL),
  ('5.1', 'ABREVIADA_TVEC', NULL),
  ('5.4', 'ABREVIADA_TVEC', NULL),
  ('5.5', 'LICITACION_PUBLICA', NULL),
  ('5.5', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('5.5', 'CONTRATACION_DIRECTA', NULL),
  ('5.6', 'CONTRATACION_DIRECTA', NULL),
  ('5.7', 'MINIMA_CUANTIA', NULL),
  ('5.7', 'REGIMEN_ESPECIAL_092', NULL),
  ('5.7', 'CONTRATACION_DIRECTA', NULL),
  ('5.8', 'ENAJENACION_SUBASTA', NULL),
  ('5.9', 'LICITACION_PUBLICA', NULL),
  ('5.9', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('5.9', 'ENAJENACION_SUBASTA', NULL),
  ('5.9', 'ABREVIADA_TVEC', NULL),
  ('5.9', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('5.9', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('5.9', 'MINIMA_CUANTIA', NULL),
  ('5.9', 'REGIMEN_ESPECIAL_092', NULL),
  ('5.9', 'CONTRATACION_DIRECTA', NULL),
  ('5.10', 'LICITACION_PUBLICA', NULL),
  ('5.10', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('5.10', 'ENAJENACION_SUBASTA', NULL),
  ('5.10', 'ABREVIADA_TVEC', NULL),
  ('5.10', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('5.10', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('5.10', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('5.10', 'MINIMA_CUANTIA', NULL),
  ('5.10', 'REGIMEN_ESPECIAL_092', NULL),
  ('5.10', 'CONTRATACION_DIRECTA', NULL),
  ('5.11', 'LICITACION_PUBLICA', NULL),
  ('5.11', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('5.11', 'ENAJENACION_SUBASTA', NULL),
  ('5.11', 'ABREVIADA_TVEC', NULL),
  ('5.11', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('5.11', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('5.11', 'MINIMA_CUANTIA', NULL),
  ('5.11', 'REGIMEN_ESPECIAL_092', NULL),
  ('5.11', 'CONTRATACION_DIRECTA', NULL),
  ('5.12', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('5.12', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('5.12', 'ENAJENACION_SUBASTA', NULL),
  ('5.12', 'ABREVIADA_TVEC', NULL),
  ('5.12', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('5.12', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('5.12', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('5.12', 'MINIMA_CUANTIA', NULL),
  ('5.12', 'REGIMEN_ESPECIAL_092', NULL),
  ('5.12', 'CONTRATACION_DIRECTA', NULL),
  ('5.13', 'ABREVIADA_TVEC', NULL),
  ('5.13', 'CONTRATACION_DIRECTA', NULL),
  ('6.1', 'CONTRATACION_DIRECTA', NULL),
  ('6.2', 'CONTRATACION_DIRECTA', NULL),
  ('6.3', 'CONTRATACION_DIRECTA', NULL),
  ('6.4', 'CONTRATACION_DIRECTA', NULL),
  ('6.5', 'CONTRATACION_DIRECTA', NULL),
  ('6.6', 'CONTRATACION_DIRECTA', NULL),
  ('6.7', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('6.7', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('6.7', 'ENAJENACION_SUBASTA', NULL),
  ('6.7', 'ABREVIADA_TVEC', NULL),
  ('6.7', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('6.7', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('6.7', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('6.7', 'MINIMA_CUANTIA', NULL),
  ('6.7', 'REGIMEN_ESPECIAL_092', NULL),
  ('6.7', 'CONTRATACION_DIRECTA', NULL),
  ('6.8', 'LICITACION_PUBLICA', NULL),
  ('6.8', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('6.8', 'ABREVIADA_TVEC', NULL),
  ('6.8', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('6.8', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('6.8', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('6.8', 'MINIMA_CUANTIA', NULL),
  ('6.8', 'REGIMEN_ESPECIAL_092', NULL),
  ('6.8', 'CONTRATACION_DIRECTA', NULL),
  ('6.9', 'LICITACION_PUBLICA', NULL),
  ('6.9', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('6.9', 'ABREVIADA_TVEC', NULL),
  ('6.9', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('6.9', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('6.9', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('6.9', 'MINIMA_CUANTIA', NULL),
  ('6.9', 'REGIMEN_ESPECIAL_092', NULL),
  ('6.9', 'CONTRATACION_DIRECTA', NULL),
  ('6.10', 'LICITACION_PUBLICA', NULL),
  ('6.10', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('6.10', 'ABREVIADA_TVEC', NULL),
  ('6.10', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('6.10', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('6.10', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('6.10', 'MINIMA_CUANTIA', NULL),
  ('6.10', 'REGIMEN_ESPECIAL_092', NULL),
  ('6.10', 'CONTRATACION_DIRECTA', NULL),
  ('7.1', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('7.1', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('7.1', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('7.1', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('7.1', 'MINIMA_CUANTIA', NULL),
  ('7.1', 'REGIMEN_ESPECIAL_092', NULL),
  ('7.1', 'CONTRATACION_DIRECTA', NULL),
  ('7.2', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('7.2', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('7.2', 'ENAJENACION_SUBASTA', NULL),
  ('7.2', 'ABREVIADA_TVEC', NULL),
  ('7.2', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('7.2', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('7.2', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('7.2', 'MINIMA_CUANTIA', NULL),
  ('7.2', 'REGIMEN_ESPECIAL_092', NULL),
  ('7.2', 'CONTRATACION_DIRECTA', NULL),
  ('7.3', 'CONTRATACION_DIRECTA', NULL),
  ('7.4', 'ABREVIADA_TVEC', NULL),
  ('8.3', 'ENAJENACION_SUBASTA', NULL),
  ('8.4', 'ENAJENACION_SUBASTA', NULL),
  ('8.5', 'LICITACION_PUBLICA', NULL),
  ('8.5', 'ABREVIADA_MENOR_CUANTIA', NULL),
  ('8.5', 'ABREVIADA_SUBASTA_INVERSA', NULL),
  ('8.5', 'ENAJENACION_SUBASTA', NULL),
  ('8.5', 'ABREVIADA_TVEC', NULL),
  ('8.5', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('8.5', 'CONCURSO_MERITOS_ABIERTO', NULL),
  ('8.5', 'CONCURSO_MERITOS_PRECAL', NULL),
  ('8.5', 'MINIMA_CUANTIA', NULL),
  ('8.5', 'REGIMEN_ESPECIAL_092', NULL),
  ('8.7', 'ENAJENACION_SUBASTA', NULL),
  ('8.8', 'ABREVIADA_BOLSA_MERCANTIL', NULL),
  ('9.4', 'ENAJENACION_SUBASTA', NULL)
ON CONFLICT (numeral, modalidad) DO UPDATE SET motivo = EXCLUDED.motivo;